/**
 * CX ENERTECH official EV package catalog seed.
 * Naming: CX Station + CX DC (S/J) + CX AC — bilingual TH/EN
 * Equipment sell prices from charger-price-rates.ts sellPrice
 * Specs mapped from ZeedaDirect / ZEC / AC datasheets
 */

export type SeedPackage = {
  id: string
  slug: string
  code: string
  name: string
  nameTh: string
  productType: 'equipment' | 'turnkey' | 'investment'
  sourceLabel: string
  tagline: string
  description: string
  powerKwMin: number
  powerKwMax: number
  chargerCount: number | null
  nozzleCountMin: number
  nozzleCountMax: number
  parkingBays: number | null
  transformerKva: number | null
  footprintWm: number | null
  footprintDm: number | null
  priceList: number | null
  pricePromo: number | null
  priceCapex: number | null
  priceNote: string
  roiAnnualPct: number | null
  paybackMonths: number | null
  netProfitMonthly: number | null
  specs: Record<string, string | number>
  includes: string[]
  features: string[]
  financials: Record<string, string | number> | null
  targetSites: string[]
  sortOrder: number
  /** Optional card/detail image path under /public */
  image?: string | null
  /** Link to charger-price-rates.ts */
  priceRateId?: string | null
  /** Link to charger-specs.ts */
  specId?: string | null
}

export const EV_PACKAGE_SEED: SeedPackage[] = [
  {
    id: 'pkg-cx-s4',
    slug: 'cx-station-s4',
    code: 'CX-S4',
    name: 'CX Station S4',
    nameTh: 'สถานีชาร์จ CX Station S4',
    productType: 'investment',
    sourceLabel: 'CX ENERTECH · Station Investment Series',
    tagline: '2× DC 120 kW · 4 charging bays · Ready-to-run investment / แพ็กเกจลงทุนพร้อมใช้งาน',
    description:
      'Entry-size CX ENERTECH charging station with chargers, electrical works, canopy, CCTV, and investor revenue model — แพ็กเกจสถานีขนาดเริ่มต้น ครบเครื่องชาร์จ ระบบไฟฟ้า โครงสร้างหลังคา กล้องวงจรปิด และโมเดลรายได้',
    powerKwMin: 240,
    powerKwMax: 240,
    chargerCount: 2,
    nozzleCountMin: 4,
    nozzleCountMax: 4,
    parkingBays: 4,
    transformerKva: 400,
    footprintWm: 12,
    footprintDm: 6.5,
    priceList: null,
    pricePromo: null,
    priceCapex: 3270000,
    priceNote: 'CAPEX อ้างอิงรวมอุปกรณ์ ติดตั้ง และ commissioning',
    roiAnnualPct: 84,
    paybackMonths: 14.3,
    netProfitMonthly: 228960,
    specs: {
      chargers: '2 × DC Fast Charger 120 kW',
      nozzles: '4 (2 ต่อเครื่อง)',
      totalPowerKw: 240,
      electrical: '240 kVA / MDB + Transformer 400 kVA',
      footprint: '12.0 × 6.5 m',
      cctv: '4 กล้อง + NVR',
    },
    includes: [
      'เครื่องชาร์จ DC 120 kW จำนวน 2 ตู้',
      'ระบบไฟฟ้าแรงสูง/ต่ำ · MDB · Transformer 400 kVA',
      'โครงสร้างหลังคา / canopy',
      'งานจุดจอด EV 4 ช่อง · landscaping · ป้ายสถานี',
      'ระบบสื่อสาร / Internet',
      'CCTV 4 กล้อง + NVR',
      'ทดสอบและ commissioning',
    ],
    features: [
      'มาตรฐานความปลอดภัย',
      'ชาร์จเร็ว เสถียร',
      'เหมาะกับพื้นที่เริ่มต้น',
      'พร้อมโมเดลลงทุนและประมาณการรายได้',
    ],
    financials: {
      operatingHoursPerDay: 10,
      kwhPerDay: 2400,
      kwhPerMonth: 72000,
      sellPricePerKwh: 8,
      energyCostPerKwh: 2.8,
      revenueMonthly: 576000,
      platformFeePct: 12,
      gpSharePct: 25,
      coordinatorPct: 10,
      investorPct: 90,
      investorNetMonthly: 228960,
      annualNet: 2747520,
      roiAnnualPct: 84,
      paybackMonths: 14.3,
    },
    targetSites: ['commercial', 'sme', 'office', 'factory'],
    sortOrder: 10,
    image: '/images/packages/cx-station-s4.jpg',
  },
  {
    id: 'pkg-cx-s10',
    slug: 'cx-station-s10',
    code: 'CX-S10',
    name: 'CX Station S10',
    nameTh: 'สถานีชาร์จ CX Station S10',
    productType: 'investment',
    sourceLabel: 'CX ENERTECH · Station Investment Series',
    tagline: '5× DC 120 kW · 10 bays · 600 kW total / สถานีทราฟฟิกสูง',
    description:
      'Mid-to-large station for high-traffic sites with full structure, electrical works, and landowner revenue share — สถานีขนาดกลาง-ใหญ่ ครบโครงสร้าง ไฟฟ้า และโมเดลแบ่งรายได้กับเจ้าของที่ดิน',
    powerKwMin: 600,
    powerKwMax: 600,
    chargerCount: 5,
    nozzleCountMin: 10,
    nozzleCountMax: 10,
    parkingBays: 10,
    transformerKva: 1000,
    footprintWm: 30,
    footprintDm: 7.5,
    priceList: null,
    pricePromo: null,
    priceCapex: 9000000,
    priceNote: 'CAPEX อ้างอิงรวมอุปกรณ์ ติดตั้ง และ commissioning',
    roiAnnualPct: 67.2,
    paybackMonths: 17.9,
    netProfitMonthly: 453600,
    specs: {
      chargers: '5 × DC Fast Charger 120 kW',
      nozzles: '10 (2 ต่อเครื่อง)',
      totalPowerKw: 600,
      electrical: 'Transformer 1,000 kVA + MDB',
      footprint: '30.0 × 7.5 m',
      cctv: '4 กล้อง + NVR',
    },
    includes: [
      'เครื่องชาร์จ DC 120 kW จำนวน 5 ตู้',
      'ระบบไฟฟ้าแรงสูง · Transformer 1,000 kVA · MDB',
      'โครงสร้างหลังคา / canopy',
      'งานจุดจอด EV 10 ช่อง · landscaping',
      'ป้ายสถานี CX ENERTECH',
      'ระบบสื่อสาร / Internet',
      'CCTV 4 กล้อง + NVR',
      'ทดสอบและ commissioning',
    ],
    features: [
      'รองรับทราฟฟิกสูง',
      'Layout สถานีมาตรฐาน',
      'โมเดลแบ่งรายได้เจ้าของที่ดิน',
      'เหมาะกับห้าง ปั๊ม และแหล่งท่องเที่ยว',
    ],
    financials: {
      operatingHoursPerDay: 10,
      kwhPerDay: 6000,
      kwhPerMonth: 180000,
      sellPricePerKwh: 8,
      energyCostPerKwh: 2.8,
      revenueMonthly: 1440000,
      landOwnerPctOfRevenue: 15,
      platformFeePct: 15,
      coordinatorPct: 10,
      investorPct: 90,
      investorNetMonthly: 453600,
      annualNet: 6048000,
      roiAnnualPct: 67.2,
      paybackMonths: 17.9,
    },
    targetSites: ['tourism', 'mall', 'gas', 'public'],
    sortOrder: 20,
    image: '/images/packages/cx-station-s10.jpg',
  },
  {
    id: 'pkg-cx-hub',
    slug: 'cx-station-hub',
    code: 'CX-HUB',
    name: 'CX Station Hub',
    nameTh: 'สถานีชาร์จ CX Station Hub',
    productType: 'turnkey',
    sourceLabel: 'CX ENERTECH · Hub Series',
    tagline: '480–960 kW · 2–12 bays · Scalable hub / ปรับขนาดตามพื้นที่',
    description:
      'High-capacity Hub package with configurable dispensers for gas stations, malls, hotels, and public parking — แพ็กเกจ Hub ความจุสูง ปรับจำนวนหัวชาร์จตามพื้นที่',
    powerKwMin: 480,
    powerKwMax: 960,
    chargerCount: 1,
    nozzleCountMin: 2,
    nozzleCountMax: 12,
    parkingBays: null,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: null,
    pricePromo: 5590000,
    priceCapex: 5590000,
    priceNote: 'ราคาเริ่มต้นรวม VAT · รวมตู้ชาร์จ Power Cabinet ติดตั้ง และบริการหลังการขาย',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      powerRangeKw: '480–960',
      nozzles: '2–12 (ปรับได้)',
      architecture: 'Power Cabinet + DC Dispenser',
      warrantyYears: 2,
    },
    includes: [
      'High-power DC Charger',
      'Power Cabinet',
      'ติดตั้งและทดสอบระบบ',
      'บริการหลังการขาย',
      'รับประกัน 2 ปี',
    ],
    features: [
      'ชาร์จหลายคันพร้อมกัน',
      'ระบบป้องกันครบ',
      'ทำงานต่อเนื่อง 24/7',
      'ขยายหัวชาร์จตามพื้นที่',
    ],
    financials: null,
    targetSites: ['gas', 'mall', 'hotel', 'office', 'parking'],
    sortOrder: 30,
    image: '/images/packages/cx-station-hub.jpg',
  },

  {
    id: 'pkg-cx-dc30',
    slug: 'cx-dc-30',
    code: 'CX-DC30',
    name: 'CX DC 30 (J1)',
    nameTh: 'เครื่องชาร์จ CX DC 30 (J1)',
    productType: 'equipment',
    sourceLabel: 'ZeedaDirect ZD-DC-J1 · 30-60 kW.pdf',
    tagline: '30 kW · CCS2 · ZD-DC-J1 / ธุรกิจขนาดเล็ก-กลาง',
    description:
      '30 kW single-gun DC charger on ZeedaDirect J1 platform — เครื่องชาร์จ DC 30 kW หัวเดียว แพลตฟอร์ม J1 สำหรับโรงแรม ร้านอาหาร และ SME',
    powerKwMin: 30,
    powerKwMax: 30,
    chargerCount: 1,
    nozzleCountMin: 1,
    nozzleCountMax: 1,
    parkingBays: 1,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: null,
    pricePromo: null,
    priceCapex: null,
    priceNote: 'ยังไม่อยู่ในตารางราคาขาย — ขอใบเสนอราคา / Not on sell-price sheet — request quote',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      model: 'ZD-DC-J1',
      power: '30 kW',
      ratedVoltage: 'CCS2 1000V DC',
      maxCurrent: 'CCS2 100A',
      cables: 'Single',
      ipRating: 'IP54',
      protocol: 'OCPP1.6J / OCPP2.0',
      screen: '8" LCD',
      dimensions: '690 × 584 × 1686 mm',
    },
    includes: ['ZD-DC-J1 30 kW', 'CCS2 cable', '8" touchscreen', 'OCPP ready'],
    features: [
      'Opportunity / destination charging',
      'Modular · CE / TUV SUD',
      'Remote monitoring + OTA',
      'Ideal for hotel / F&B / SME',
    ],
    financials: null,
    targetSites: ['hotel', 'restaurant', 'sme', 'factory'],
    sortOrder: 40,
    image: '/images/packages/cx-dc-j1.jpg',
    priceRateId: null,
    specId: 'spec-zd-j1',
  },
  {
    id: 'pkg-cx-dc40',
    slug: 'cx-dc-40',
    code: 'CX-DC40',
    name: 'CX DC 40 (J2)',
    nameTh: 'เครื่องชาร์จ CX DC 40 (J2)',
    productType: 'equipment',
    sourceLabel: 'ZeedaDirect ZD-DC-J2 · 40-160 kW.pdf',
    tagline: '40 kW · CCS2 200A · ZD-DC-J2 / เชิงพาณิชย์ความเร็วกลาง',
    description:
      '40 kW DC charger on ZeedaDirect J2 platform (40–160 kW family) — เครื่องชาร์จ DC 40 kW แพลตฟอร์ม J2',
    powerKwMin: 40,
    powerKwMax: 40,
    chargerCount: 1,
    nozzleCountMin: 1,
    nozzleCountMax: 2,
    parkingBays: 1,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: null,
    pricePromo: null,
    priceCapex: null,
    priceNote: 'ยังไม่อยู่ในตารางราคาขาย — ขอใบเสนอราคา / Not on sell-price sheet — request quote',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      model: 'ZD-DC-J2',
      power: '40 kW',
      ratedVoltage: 'CCS2 1000V DC',
      maxCurrent: 'CCS2 200A',
      ipRating: 'IP54',
      protocol: 'OCPP1.6J / OCPP2.0.1',
      screen: '8" LCD',
      auth: 'APP / RFID / NFC / Credit Card',
      dimensions: '700 × 490 × 1696 mm',
    },
    includes: ['ZD-DC-J2 40 kW', 'CCS2 cables', '8" touchscreen', 'OCPP ready'],
    features: ['Modular mid-power platform', 'Multi-auth payment ready', 'CE / TUV SUD', 'OTA upgrades'],
    financials: null,
    targetSites: ['commercial', 'mall', 'office'],
    sortOrder: 45,
    image: '/images/packages/cx-dc-j2.jpg',
    priceRateId: null,
    specId: 'spec-zd-j2',
  },
  {
    id: 'pkg-cx-dc60',
    slug: 'cx-dc-60',
    code: 'CX-DC60',
    name: 'CX DC 60 S (ZEC)',
    nameTh: 'เครื่องชาร์จ CX DC 60 S (ZEC)',
    productType: 'equipment',
    sourceLabel: 'ZEC 60kW DC Charger · S-Series price sheet',
    tagline: '60 kW · S-Series · Sell 468,000 / ราคาแนะนำขาย',
    description:
      'ZEC 60 kW integrated DC fast charger — เครื่องชาร์จ DC 60 kW ไลน์ S-Series พร้อมตารางราคาขาย-ต้นทุน',
    powerKwMin: 60,
    powerKwMax: 60,
    chargerCount: 1,
    nozzleCountMin: 1,
    nozzleCountMax: 2,
    parkingBays: 1,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: 468000,
    pricePromo: 360000,
    priceCapex: null,
    priceNote:
      'ราคาแนะนำขาย 468,000 · ต้นทุนเริ่ม 360,000 (<3, S-Series) / Sell 468k · Cost from 360k',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      model: 'ZEC-60',
      series: 'S-Series',
      input: '400 VAC ±10% · 3P+N+PE · 112 A',
      ratedPower: 'DC 60 kW',
      outputVoltage: 'CCS2 200–1000 Vdc',
      efficiency: '96%',
      ipIk: 'IP55 / IK10',
      protocol: 'OCPP 1.6J',
    },
    includes: ['ZEC 60 kW DC Fast Charger', 'CCS2 cable 5 m', 'RFID / OCPP 1.6J', 'CE / TUV'],
    features: ['S-Series sell/cost tiers', 'Multi-connector options', 'IP55/IK10', 'Compact integrated'],
    financials: null,
    targetSites: ['commercial', 'mall', 'depot', 'station'],
    sortOrder: 50,
    image: '/images/packages/cx-dc-60.jpg',
    priceRateId: 'rate-dc-s-60',
    specId: 'spec-zec-60',
  },
  {
    id: 'pkg-cx-dc60-j',
    slug: 'cx-dc-60-j',
    code: 'CX-DC60-J',
    name: 'CX DC 60 J',
    nameTh: 'เครื่องชาร์จ CX DC 60 J',
    productType: 'equipment',
    sourceLabel: 'ZeedaDirect ZD-DC-J1 · J-Series price sheet',
    tagline: '60 kW · J-Series · Sell 364,000 / ราคาแนะนำขาย',
    description:
      '60 kW dual-ready DC on ZeedaDirect J1 — เครื่องชาร์จ DC 60 kW ไลน์ J-Series ราคาแนะนำขายจากตารางราคา',
    powerKwMin: 60,
    powerKwMax: 60,
    chargerCount: 1,
    nozzleCountMin: 1,
    nozzleCountMax: 2,
    parkingBays: 1,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: 364000,
    pricePromo: 280000,
    priceCapex: null,
    priceNote:
      'ราคาแนะนำขาย 364,000 · ต้นทุนเริ่ม 280,000 (<3, J-Series) / Sell 364k · Cost from 280k',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      model: 'ZD-DC-J1',
      series: 'J-Series',
      power: '60 kW',
      ratedVoltage: 'CCS2 1000V DC',
      maxCurrent: 'CCS2 200A',
      cables: 'Dual',
      ipRating: 'IP54',
      protocol: 'OCPP1.6J / OCPP2.0',
      screen: '8" LCD',
      dimensions: '690 × 584 × 1686 mm',
    },
    includes: ['ZD-DC-J1 60 kW', 'Dual CCS2 ready', '8" touchscreen', 'OCPP ready'],
    features: ['J-Series sell/cost tiers', 'CE / TUV SUD', 'Remote + OTA', 'Destination charging'],
    financials: null,
    targetSites: ['commercial', 'mall', 'hotel', 'sme'],
    sortOrder: 52,
    image: '/images/packages/cx-dc-j1.jpg',
    priceRateId: 'rate-dc-j-60',
    specId: 'spec-zd-j1',
  },
  {
    id: 'pkg-cx-dc120',
    slug: 'cx-dc-120',
    code: 'CX-DC120',
    name: 'CX DC 120 S (ZEC)',
    nameTh: 'เครื่องชาร์จ CX DC 120 S (ZEC)',
    productType: 'equipment',
    sourceLabel: 'ZEC 120kW DC Charger · S-Series price sheet',
    tagline: '120 kW · S-Series · Sell 676,000 / ราคาแนะนำขาย',
    description:
      'ZEC 120 kW outdoor integrated DC charger — เครื่องชาร์จ DC 120 kW ไลน์ S-Series พร้อมตารางราคาขาย-ต้นทุน',
    powerKwMin: 120,
    powerKwMax: 120,
    chargerCount: 1,
    nozzleCountMin: 1,
    nozzleCountMax: 2,
    parkingBays: 2,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: 676000,
    pricePromo: 520000,
    priceCapex: null,
    priceNote:
      'ราคาแนะนำขาย 676,000 · ต้นทุนเริ่ม 520,000 (<3, S-Series) / Sell 676k · Cost from 520k',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      model: 'ZEC-120',
      series: 'S-Series',
      input: '400 VAC ±10% · 3P+N+PE · 224 A',
      ratedPower: 'DC 120 kW',
      outputVoltage: 'CCS2 200–1000 Vdc',
      efficiency: '96%',
      ipIk: 'IP55 / IK10',
      protocol: 'OCPP 1.6J',
    },
    includes: ['ZEC 120 kW DC Fast Charger', 'CCS2 cable 5 m', 'RFID / OCPP 1.6J', 'CE / TUV'],
    features: ['S-Series sell/cost tiers', 'Single or dual connector', 'IP55/IK10', 'Power sharing'],
    financials: null,
    targetSites: ['station', 'mall', 'gas', 'depot'],
    sortOrder: 55,
    image: '/images/packages/cx-dc-120.jpg',
    priceRateId: 'rate-dc-s-120',
    specId: 'spec-zec-120',
  },
  {
    id: 'pkg-cx-dc120-j',
    slug: 'cx-dc-120-j',
    code: 'CX-DC120-J',
    name: 'CX DC 120 J',
    nameTh: 'เครื่องชาร์จ CX DC 120 J',
    productType: 'equipment',
    sourceLabel: 'ZeedaDirect ZD-DC-J2 · J-Series price sheet',
    tagline: '120 kW · J-Series · Sell 494,000 / ราคาแนะนำขาย',
    description:
      '120 kW DC on ZeedaDirect J2 (40–160 kW family) — เครื่องชาร์จ DC 120 kW ไลน์ J-Series จากตารางราคา',
    powerKwMin: 120,
    powerKwMax: 120,
    chargerCount: 1,
    nozzleCountMin: 1,
    nozzleCountMax: 2,
    parkingBays: 2,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: 494000,
    pricePromo: 380000,
    priceCapex: null,
    priceNote:
      'ราคาแนะนำขาย 494,000 · ต้นทุนเริ่ม 380,000 (<3, J-Series) / Sell 494k · Cost from 380k',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      model: 'ZD-DC-J2',
      series: 'J-Series',
      power: '120 kW',
      ratedVoltage: 'CCS2 1000V DC',
      maxCurrent: 'CCS2 200A',
      cableLength: '5m × 2 or 7m × 2',
      ipRating: 'IP54',
      protocol: 'OCPP1.6J / OCPP2.0.1',
      auth: 'APP / RFID / NFC / Credit Card',
      dimensions: '700 × 490 × 1696 mm',
    },
    includes: ['ZD-DC-J2 120 kW', 'Dual CCS2 ready', '8" touchscreen', 'OCPP ready'],
    features: ['J-Series sell/cost tiers', 'Multi-auth payment', 'CE / TUV SUD', 'OTA upgrades'],
    financials: null,
    targetSites: ['station', 'mall', 'gas', 'commercial'],
    sortOrder: 57,
    image: '/images/packages/cx-dc-j2.jpg',
    priceRateId: 'rate-dc-j-120',
    specId: 'spec-zd-j2',
  },
  {
    id: 'pkg-cx-dc180',
    slug: 'cx-dc-180',
    code: 'CX-DC180',
    name: 'CX DC 180 J',
    nameTh: 'เครื่องชาร์จ CX DC 180 J',
    productType: 'equipment',
    sourceLabel: 'ZeedaDirect ZD-DC-J3 · 160-240 kW.pdf',
    tagline: '180 kW · J3 platform · Price pending / รออัปเดตราคา',
    description:
      '180 kW DC on ZeedaDirect J3 (160/180/240 kW) — เครื่องชาร์จ DC 180 kW แพลตฟอร์ม J3 (รอราคาในตาราง J-Series)',
    powerKwMin: 180,
    powerKwMax: 180,
    chargerCount: 1,
    nozzleCountMin: 2,
    nozzleCountMax: 2,
    parkingBays: 2,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: null,
    pricePromo: null,
    priceCapex: null,
    priceNote: 'รออัปเดตราคา J-Series 180 kW / Price pending on J-Series sheet',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      model: 'ZD-DC-J3',
      series: 'J-Series',
      power: '180 kW',
      ratedVoltage: 'CCS2 1000V DC',
      maxCurrent: 'CCS2 250A',
      cableLength: '5m × 2 or 7m × 2',
      ipRating: 'IP54',
      protocol: 'OCPP 1.6J / 2.0.1',
      screen: '8" LCD',
      dimensions: '750 × 605 × 1805 mm',
    },
    includes: ['ZD-DC-J3 180 kW', 'Dual connector', '8" touchscreen', 'OCPP ready'],
    features: ['High-power station ready', 'Multi-auth payment', 'CE / TUV SUD', 'OTA upgrades'],
    financials: null,
    targetSites: ['station', 'hub', 'gas', 'depot'],
    sortOrder: 60,
    image: '/images/packages/cx-dc-j3.jpg',
    priceRateId: 'rate-dc-j-180',
    specId: 'spec-zd-j3',
  },
  {
    id: 'pkg-cx-dc240-j',
    slug: 'cx-dc-240-j',
    code: 'CX-DC240-J',
    name: 'CX DC 240 J',
    nameTh: 'เครื่องชาร์จ CX DC 240 J',
    productType: 'equipment',
    sourceLabel: 'ZeedaDirect ZD-DC-J3 / J4 · 160-240 & 240-420 kW.pdf',
    tagline: '240 kW · J3/J4 · Price pending / รออัปเดตราคา',
    description:
      '240 kW DC available on J3 (160–240) or J4 (240–420) platforms — เครื่องชาร์จ DC 240 kW (รอราคาในตาราง J-Series)',
    powerKwMin: 240,
    powerKwMax: 240,
    chargerCount: 1,
    nozzleCountMin: 2,
    nozzleCountMax: 2,
    parkingBays: 2,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: null,
    pricePromo: null,
    priceCapex: null,
    priceNote: 'รออัปเดตราคา J-Series 240 kW / Price pending on J-Series sheet',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      model: 'ZD-DC-J3 / J4',
      series: 'J-Series',
      power: '240 kW',
      ratedVoltage: 'CCS2 1000V DC',
      maxCurrent: 'CCS2 400A',
      ipRating: 'IP54',
      protocol: 'OCPP1.6J / OCPP2.0',
      screen: '8" LCD',
    },
    includes: ['ZD-DC-J3 or J4 240 kW', 'Dual connector', '8" touchscreen', 'OCPP ready'],
    features: ['Ultra-fast corridor ready', 'Multi-auth payment', 'CE certified', 'OTA upgrades'],
    financials: null,
    targetSites: ['hub', 'highway', 'depot', 'gas'],
    sortOrder: 62,
    image: '/images/packages/cx-dc-j4.jpg',
    priceRateId: 'rate-dc-j-240',
    specId: 'spec-zd-j4',
  },
  {
    id: 'pkg-cx-dc30p',
    slug: 'cx-dc-30-pay',
    code: 'CX-DC30P',
    name: 'CX DC 30 Pay',
    nameTh: 'เครื่องชาร์จ CX DC 30 Pay',
    productType: 'equipment',
    sourceLabel: 'CX ENERTECH · DC Pay Series',
    tagline: '30 kW · RFID/QR · Payment ready / พร้อมระบบชำระเงิน',
    description:
      'DC 30 kW charger with built-in payment — เครื่องชาร์จ DC 30 kW พร้อมระบบชำระเงินในตัว สำหรับโรงแรม ร้านอาหาร และ SME',
    powerKwMin: 30,
    powerKwMax: 30,
    chargerCount: 1,
    nozzleCountMin: 1,
    nozzleCountMax: 1,
    parkingBays: 1,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: 179000,
    pricePromo: 179000,
    priceCapex: null,
    priceNote: 'ราคาเครื่องอ้างอิงรวมระบบชำระเงิน / Includes payment system',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      model: 'CX DC 30 Pay',
      powerKw: 30,
      auth: 'RFID + QR',
      payment: 'Scan to Pay',
      display: 'Yes',
    },
    includes: ['CX DC 30 Pay', 'Scan to Pay', 'Display', 'RFID / QR'],
    features: [
      'Up to 30 kW DC',
      'Safety certified platform',
      'Easy display UI',
      'Ready for paid charging',
    ],
    financials: null,
    targetSites: ['hotel', 'restaurant', 'factory', 'sme'],
    sortOrder: 70,
    image: '/images/packages/cx-dc-30-pay.jpg',
    priceRateId: null,
    specId: null,
  },
  {
    id: 'pkg-cx-ac7-g',
    slug: 'cx-ac-7-g',
    code: 'CX-AC7-G',
    name: 'CX AC 7 G',
    nameTh: 'เครื่องชาร์จ CX AC 7 G',
    productType: 'equipment',
    sourceLabel: 'ZD Energy G Series · AC price sheet',
    tagline: '7.4 kW · 1P · Sell 13,500 / ราคาแนะนำขาย',
    description:
      'G-Series 7.4 kW single-phase AC wallbox — เครื่องชาร์จ AC G-Series ราคาแนะนำขายจากตารางราคา AC',
    powerKwMin: 7,
    powerKwMax: 7,
    chargerCount: 1,
    nozzleCountMin: 1,
    nozzleCountMax: 1,
    parkingBays: 1,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: 13500,
    pricePromo: 7500,
    priceCapex: null,
    priceNote: 'ราคาแนะนำขาย 13,500 · ต้นทุนเริ่ม 7,500 (<3) / Sell 13.5k · Cost from 7.5k',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      model: 'ZD-AC-G',
      series: 'G-Series',
      power: '7.4 kW (3.7 option)',
      voltage: 'AC 230V',
      current: '32A',
      phase: '1P',
      ipRating: 'IP55',
      protocol: 'OCPP1.6JSON',
      dimensions: '310 × 214 × 90 mm',
    },
    includes: ['G-Series 7.4 kW charger', '7 m cable', 'Wall mount', 'Optional RFID'],
    features: ['Compact & light', 'Home / light commercial', 'OCPP ready', 'Multi-protection'],
    financials: null,
    targetSites: ['home', 'condo', 'sme', 'office'],
    sortOrder: 80,
    image: '/images/packages/cx-ac-g7.jpg',
    priceRateId: 'rate-ac-g-7',
    specId: 'spec-ac-g-7',
  },
  {
    id: 'pkg-cx-ac7-k',
    slug: 'cx-ac-7-k',
    code: 'CX-AC7-K',
    name: 'CX AC 7 K',
    nameTh: 'เครื่องชาร์จ CX AC 7 K',
    productType: 'equipment',
    sourceLabel: 'ZD Energy K Series · AC price sheet',
    tagline: '7.4 kW · 1P · IP66 · Sell 15,300 / ราคาแนะนำขาย',
    description:
      'K-Series 7.4 kW rugged AC wallbox (IP66 shell) — เครื่องชาร์จ AC K-Series เปลือกกันน้ำสูง ราคาจากตาราง AC',
    powerKwMin: 7,
    powerKwMax: 7,
    chargerCount: 1,
    nozzleCountMin: 1,
    nozzleCountMax: 1,
    parkingBays: 1,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: 15300,
    pricePromo: 8500,
    priceCapex: null,
    priceNote: 'ราคาแนะนำขาย 15,300 · ต้นทุนเริ่ม 8,500 (<3) / Sell 15.3k · Cost from 8.5k',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      model: 'ZD-AC-K',
      series: 'K-Series',
      power: '7.4 kW (3.7 option)',
      voltage: 'AC 230V',
      current: '32A',
      phase: '1P',
      ipRating: 'IP66 shell / IP55 gun',
      protocol: 'OCPP 1.6 JSON',
      dimensions: '420 × 251 × 145 mm',
    },
    includes: ['K-Series 7.4 kW charger', '7 m cable', 'Wall mount', 'Optional RFID / WiFi'],
    features: ['IP66 outdoor shell', 'OCPP ready', 'Multi-protection', 'Pedestal option'],
    financials: null,
    targetSites: ['home', 'condo', 'parking', 'sme'],
    sortOrder: 82,
    image: '/images/packages/cx-ac-k7.jpg',
    priceRateId: 'rate-ac-k-7',
    specId: 'spec-ac-k-7',
  },
  {
    id: 'pkg-cx-ac7-miniz',
    slug: 'cx-ac-7-miniz',
    code: 'CX-AC7-MINIZ',
    name: 'CX AC 7 Mini Z',
    nameTh: 'เครื่องชาร์จ CX AC 7 Mini Z',
    productType: 'equipment',
    sourceLabel: 'Mini Z-Series · AC price sheet',
    tagline: '7 kW · 1P · Sell 9,900 / ราคาแนะนำขาย',
    description:
      'Entry Mini Z-Series 7 kW AC wallbox — เครื่องชาร์จ AC รุ่นประหยัด ราคาแนะนำขายจากตาราง AC',
    powerKwMin: 7,
    powerKwMax: 7,
    chargerCount: 1,
    nozzleCountMin: 1,
    nozzleCountMax: 1,
    parkingBays: 1,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: 9900,
    pricePromo: 5500,
    priceCapex: null,
    priceNote: 'ราคาแนะนำขาย 9,900 · ต้นทุนเริ่ม 5,500 (<3) / Sell 9.9k · Cost from 5.5k',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      model: 'ZD-AC-MINIZ',
      series: 'Mini Z-Series',
      power: '7 kW',
      phase: '1P',
      form: 'Compact wallbox',
    },
    includes: ['Mini Z 7 kW charger', 'Wall mount'],
    features: ['Entry price point', 'Residential ready', 'Compact install'],
    financials: null,
    targetSites: ['home', 'condo', 'sme'],
    sortOrder: 84,
    image: '/images/packages/cx-ac-miniz.jpg',
    priceRateId: 'rate-ac-miniz-7',
    specId: 'spec-ac-miniz-7',
  },
  {
    id: 'pkg-cx-ac11-e',
    slug: 'cx-ac-11-e',
    code: 'CX-AC11-E',
    name: 'CX AC 11 E',
    nameTh: 'เครื่องชาร์จ CX AC 11 E',
    productType: 'equipment',
    sourceLabel: 'ZD Energy E Series · AC price sheet',
    tagline: '11 kW · 3P · Sell 23,400 / ราคาแนะนำขาย',
    description:
      'E-Series 11 kW three-phase AC charger — เครื่องชาร์จ AC E-Series 11 kW สามเฟส จากตารางราคา AC',
    powerKwMin: 11,
    powerKwMax: 11,
    chargerCount: 1,
    nozzleCountMin: 1,
    nozzleCountMax: 1,
    parkingBays: 1,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: 23400,
    pricePromo: 13000,
    priceCapex: null,
    priceNote: 'ราคาแนะนำขาย 23,400 · ต้นทุนเริ่ม 13,000 (<3) / Sell 23.4k · Cost from 13k',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      model: 'ZD-AC-E',
      series: 'E-Series',
      power: '11 kW',
      voltage: 'AC 400V',
      current: '16A option / 32A platform',
      phase: '3P',
      ipRating: 'IP55',
      protocol: 'OCPP1.6JSON',
      dimensions: '473 × 290 × 160 mm',
    },
    includes: ['E-Series 11 kW charger', '7 m cable', 'Wall mount', 'Optional RFID / WiFi'],
    features: ['Three-phase commercial', 'IP55', 'OCPP ready', 'Multi-protection'],
    financials: null,
    targetSites: ['office', 'hotel', 'mall', 'parking'],
    sortOrder: 86,
    image: '/images/packages/cx-ac-e.jpg',
    priceRateId: 'rate-ac-e-11',
    specId: 'spec-ac-e',
  },
  {
    id: 'pkg-cx-ac22-e',
    slug: 'cx-ac-22-e',
    code: 'CX-AC22-E',
    name: 'CX AC 22 E',
    nameTh: 'เครื่องชาร์จ CX AC 22 E',
    productType: 'equipment',
    sourceLabel: 'ZD Energy E Series · AC price sheet',
    tagline: '22 kW · 3P · Sell 27,000 / ราคาแนะนำขาย',
    description:
      'E-Series 22 kW three-phase AC charger — เครื่องชาร์จ AC E-Series 22 kW สามเฟส จากตารางราคา AC',
    powerKwMin: 22,
    powerKwMax: 22,
    chargerCount: 1,
    nozzleCountMin: 1,
    nozzleCountMax: 1,
    parkingBays: 1,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: 27000,
    pricePromo: 15000,
    priceCapex: null,
    priceNote: 'ราคาแนะนำขาย 27,000 · ต้นทุนเริ่ม 15,000 (<3) / Sell 27k · Cost from 15k',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      model: 'ZD-AC-E',
      series: 'E-Series',
      power: '22 kW',
      voltage: 'AC 400V',
      current: '32A',
      phase: '3P',
      ipRating: 'IP55',
      protocol: 'OCPP1.6JSON',
      dimensions: '473 × 290 × 160 mm',
    },
    includes: ['E-Series 22 kW charger', '7 m cable', 'Wall mount', 'Optional RFID / WiFi'],
    features: ['Fast AC commercial', 'IP55', 'OCPP ready', 'Multi-protection'],
    financials: null,
    targetSites: ['office', 'hotel', 'mall', 'parking', 'depot'],
    sortOrder: 88,
    image: '/images/packages/cx-ac-e.jpg',
    priceRateId: 'rate-ac-e-22',
    specId: 'spec-ac-e',
  },
]
