/**
 * Seed payload from market infographics (ELEXA, S4/Elexa, EV ECO TECH, EV Infinity).
 * Used to populate SQLite — reference figures for CX package catalog, not live competitor quotes.
 */

export type SeedPackage = {
  id: string
  slug: string
  code: string
  name: string
  nameTh: string
  productType: 'equipment' | 'turnkey' | 'investment'
  sourceLabel: string
  tagline: string
  description: string
  powerKwMin: number
  powerKwMax: number
  chargerCount: number | null
  nozzleCountMin: number
  nozzleCountMax: number
  parkingBays: number | null
  transformerKva: number | null
  footprintWm: number | null
  footprintDm: number | null
  priceList: number | null
  pricePromo: number | null
  priceCapex: number | null
  priceNote: string
  roiAnnualPct: number | null
  paybackMonths: number | null
  netProfitMonthly: number | null
  specs: Record<string, string | number>
  includes: string[]
  features: string[]
  financials: Record<string, string | number> | null
  targetSites: string[]
  sortOrder: number
}

export const EV_PACKAGE_SEED: SeedPackage[] = [
  {
    id: 'pkg-hub-s',
    slug: 'hub-s-starter-station',
    code: 'HUB-S',
    name: 'Starter Station',
    nameTh: 'สถานีชาร์จเริ่มต้น (Final Project)',
    productType: 'investment',
    sourceLabel: 'ELEXA EV Charging · Final Project',
    tagline: '2× DC 120 kW · 4 จุดชาร์จ · ลงทุนพร้อมโมเดลรายได้',
    description:
      'แพ็กเกจสถานีชาร์จพร้อมลงทุน ครบทั้งเครื่องชาร์จ ระบบไฟฟ้า โครงสร้างหลังคา กล้องวงจรปิด และสมมติฐานรายได้สำหรับนักลงทุน',
    powerKwMin: 240,
    powerKwMax: 240,
    chargerCount: 2,
    nozzleCountMin: 4,
    nozzleCountMax: 4,
    parkingBays: 4,
    transformerKva: 400,
    footprintWm: 12,
    footprintDm: 6.5,
    priceList: null,
    pricePromo: null,
    priceCapex: 3270000,
    priceNote: 'CAPEX อ้างอิงรวมอุปกรณ์ ติดตั้ง และ commissioning',
    roiAnnualPct: 84,
    paybackMonths: 14.3,
    netProfitMonthly: 228960,
    specs: {
      chargers: '2 × DC Fast Charger 120 kW',
      nozzles: '4 (2 ต่อเครื่อง)',
      totalPowerKw: 240,
      electrical: '240 kVA / MDB + Transformer 400 kVA',
      footprint: '12.0 × 6.5 m',
      cctv: '4 กล้อง + NVR',
    },
    includes: [
      'เครื่องชาร์จ DC 120 kW จำนวน 2 ตู้',
      'ระบบไฟฟ้าแรงสูง/ต่ำ · MDB · Transformer 400 kVA',
      'โครงสร้างหลังคา / canopy',
      'งานจุดจอด EV 4 ช่อง · landscaping · ป้ายสถานี',
      'ระบบสื่อสาร / Internet',
      'CCTV 4 กล้อง + NVR',
      'ทดสอบและ commissioning',
    ],
    features: [
      'มาตรฐานความปลอดภัย',
      'ชาร์จเร็ว เสถียร',
      'พลังงานสะอาด',
      'บริการดูแล 24 ชม. (ตามโมเดลผู้ให้บริการ)',
    ],
    financials: {
      operatingHoursPerDay: 10,
      kwhPerDay: 2400,
      kwhPerMonth: 72000,
      sellPricePerKwh: 8,
      energyCostPerKwh: 2.8,
      revenueMonthly: 576000,
      platformFeePct: 12,
      gpSharePct: 25,
      coordinatorPct: 10,
      investorPct: 90,
      investorNetMonthly: 228960,
      annualNet: 2747520,
      roiAnnualPct: 84,
      paybackMonths: 14.3,
    },
    targetSites: ['commercial', 'sme', 'office', 'factory'],
    sortOrder: 10,
  },
  {
    id: 'pkg-hub-m',
    slug: 'hub-m-growth-station',
    code: 'HUB-M',
    name: 'Growth Station',
    nameTh: 'สถานีชาร์จขยาย — ตลาดน้ำ 4 ภาค พัทยา',
    productType: 'investment',
    sourceLabel: 'S4 Smart Energy × Elexa · Pattaya Floating Market',
    tagline: '5× DC 120 kW · 10 จุดชาร์จ · กำลังรวม 600 kW',
    description:
      'แพ็กเกจสถานีขนาดกลาง-ใหญ่ สำหรับพื้นที่ทราฟฟิกสูง ครบโครงสร้าง ไฟฟ้า และโมเดลแบ่งรายได้กับเจ้าของที่ดิน',
    powerKwMin: 600,
    powerKwMax: 600,
    chargerCount: 5,
    nozzleCountMin: 10,
    nozzleCountMax: 10,
    parkingBays: 10,
    transformerKva: 1000,
    footprintWm: 30,
    footprintDm: 7.5,
    priceList: null,
    pricePromo: null,
    priceCapex: 9000000,
    priceNote: 'CAPEX อ้างอิงรวมอุปกรณ์ ติดตั้ง และ commissioning',
    roiAnnualPct: 67.2,
    paybackMonths: 17.9,
    netProfitMonthly: 453600,
    specs: {
      chargers: '5 × DC Fast Charger 120 kW',
      nozzles: '10 (2 ต่อเครื่อง)',
      totalPowerKw: 600,
      electrical: 'Transformer 1,000 kVA + MDB',
      footprint: '30.0 × 7.5 m',
      cctv: '4 กล้อง + NVR',
    },
    includes: [
      'เครื่องชาร์จ DC 120 kW จำนวน 5 ตู้',
      'ระบบไฟฟ้าแรงสูง · Transformer 1,000 kVA · MDB',
      'โครงสร้างหลังคา / canopy',
      'งานจุดจอด EV 10 ช่อง · landscaping',
      'ป้าย Elexa EV Sign',
      'ระบบสื่อสาร / Internet',
      'CCTV 4 กล้อง + NVR',
      'ทดสอบและ commissioning',
    ],
    features: [
      'รองรับทราฟฟิกสูง',
      'Layout สถานีมาตรฐาน',
      'โมเดลแบ่งรายได้เจ้าของที่ดิน',
      'เหมาะกับแหล่งท่องเที่ยว / ห้าง / ปั๊ม',
    ],
    financials: {
      operatingHoursPerDay: 10,
      kwhPerDay: 6000,
      kwhPerMonth: 180000,
      sellPricePerKwh: 8,
      energyCostPerKwh: 2.8,
      revenueMonthly: 1440000,
      landOwnerPctOfRevenue: 15,
      platformFeePct: 15,
      coordinatorPct: 10,
      investorPct: 90,
      investorNetMonthly: 453600,
      annualNet: 6048000,
      roiAnnualPct: 67.2,
      paybackMonths: 17.9,
    },
    targetSites: ['tourism', 'mall', 'gas', 'public'],
    sortOrder: 20,
  },
  {
    id: 'pkg-hub-l',
    slug: 'hub-l-custom-hub',
    code: 'HUB-L',
    name: 'Hub Station Custom',
    nameTh: 'Hub Station ความจุสูง ปรับจำนวนหัวได้',
    productType: 'turnkey',
    sourceLabel: 'EV Infinity · HUB STATION Promotion',
    tagline: '480–960 kW · 2–12 nozzles · All-in-one',
    description:
      'แพ็กเกจ Hub ความจุสูง ปรับจำนวนหัวชาร์จตามพื้นที่ เหมาะกับปั๊มน้ำมัน ห้าง โรงแรม และที่จอดรถสาธารณะ',
    powerKwMin: 480,
    powerKwMax: 960,
    chargerCount: 1,
    nozzleCountMin: 2,
    nozzleCountMax: 12,
    parkingBays: null,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: null,
    pricePromo: 5590000,
    priceCapex: 5590000,
    priceNote: 'ราคาเริ่มต้นรวม VAT · รวมตู้ชาร์จ Power Cabinet ติดตั้ง และบริการหลังการขาย',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      powerRangeKw: '480–960',
      nozzles: '2–12 (ปรับได้)',
      architecture: 'Power Cabinet + DC Dispenser',
      warrantyYears: 2,
    },
    includes: [
      'High-power DC Charger',
      'Power Cabinet',
      'ติดตั้งและทดสอบระบบ',
      'บริการหลังการขาย',
      'รับประกัน 2 ปี',
    ],
    features: [
      'ชาร์จหลายคันพร้อมกัน',
      'ระบบป้องกันครบ',
      'ทำงานต่อเนื่อง 24/7',
      'ขยายหัวชาร์จตามพื้นที่',
    ],
    financials: null,
    targetSites: ['gas', 'mall', 'hotel', 'office', 'parking'],
    sortOrder: 30,
  },
  {
    id: 'pkg-dc-30-eco',
    slug: 'dc-charger-30kw',
    code: 'DC-30',
    name: 'DC Charger 30 kW',
    nameTh: 'เครื่องชาร์จ DC 30 kW',
    productType: 'equipment',
    sourceLabel: 'EV ECO TECH · DC CHARGER',
    tagline: 'CCS2 · Single Gun · Commercial',
    description: 'เครื่องชาร์จ DC สำหรับเชิงพาณิชย์ขนาดเล็ก-กลาง พร้อมระบบป้องกันอัจฉริยะและ OCPP 1.6',
    powerKwMin: 30,
    powerKwMax: 30,
    chargerCount: 1,
    nozzleCountMin: 1,
    nozzleCountMax: 1,
    parkingBays: 1,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: 325000,
    pricePromo: 292500,
    priceCapex: null,
    priceNote: 'ราคาโปรโมชันอ้างอิง (−10%) · ยังไม่รวมติดตั้ง EPC',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      connector: 'CCS2',
      guns: 'Single Gun',
      warrantyMonths: 12,
      protocol: 'OCPP 1.6',
      ipRating: 'IP54',
      usage: 'Commercial Charging',
    },
    includes: ['เครื่องชาร์จ DC 30 kW', 'หัวชาร์จ CCS2', 'รับประกัน 12 เดือน'],
    features: [
      'Rapid charging',
      'Output split power (รองรับตามรุ่น)',
      'ป้องกันฟ้าผ่า / แรงดันเกิน-ต่ำ / ลัดวงจร',
      'ตรวจจับอุณหภูมิหัวชาร์จ',
      'Emergency stop',
    ],
    financials: null,
    targetSites: ['hotel', 'restaurant', 'sme', 'factory'],
    sortOrder: 40,
  },
  {
    id: 'pkg-dc-40-eco',
    slug: 'dc-charger-40kw',
    code: 'DC-40',
    name: 'DC Charger 40 kW',
    nameTh: 'เครื่องชาร์จ DC 40 kW',
    productType: 'equipment',
    sourceLabel: 'EV ECO TECH · DC CHARGER',
    tagline: 'CCS2 · Commercial mid-power',
    description: 'เครื่องชาร์จ DC 40 kW สำหรับธุรกิจที่ต้องการความเร็วสูงกว่า 30 kW',
    powerKwMin: 40,
    powerKwMax: 40,
    chargerCount: 1,
    nozzleCountMin: 1,
    nozzleCountMax: 1,
    parkingBays: 1,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: 389000,
    pricePromo: 350100,
    priceCapex: null,
    priceNote: 'ราคาโปรโมชันอ้างอิง (−10%) · ยังไม่รวมติดตั้ง EPC',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      connector: 'CCS2',
      guns: 'Single Gun',
      warrantyMonths: 12,
      protocol: 'OCPP 1.6',
      ipRating: 'IP54',
      usage: 'Commercial Charging',
    },
    includes: ['เครื่องชาร์จ DC 40 kW', 'หัวชาร์จ CCS2', 'รับประกัน 12 เดือน'],
    features: [
      'Rapid charging',
      'ระบบป้องกันอัจฉริยะครบชุด',
      'รองรับ OCPP 1.6',
      'IP54',
    ],
    financials: null,
    targetSites: ['commercial', 'mall', 'office'],
    sortOrder: 50,
  },
  {
    id: 'pkg-dc-60-eco',
    slug: 'dc-charger-60kw',
    code: 'DC-60',
    name: 'DC Charger 60 kW',
    nameTh: 'เครื่องชาร์จ DC 60 kW',
    productType: 'equipment',
    sourceLabel: 'EV ECO TECH · DC CHARGER',
    tagline: 'CCS2 · Fast commercial',
    description: 'เครื่องชาร์จ DC 60 kW สำหรับจุดบริการที่ต้องการชาร์จเร็วในเชิงพาณิชย์',
    powerKwMin: 60,
    powerKwMax: 60,
    chargerCount: 1,
    nozzleCountMin: 1,
    nozzleCountMax: 1,
    parkingBays: 1,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: 699000,
    pricePromo: 629100,
    priceCapex: null,
    priceNote: 'ราคาโปรโมชันอ้างอิง (−10%) · ยังไม่รวมติดตั้ง EPC',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      connector: 'CCS2',
      guns: 'Single / Split',
      warrantyMonths: 12,
      protocol: 'OCPP 1.6',
      ipRating: 'IP54',
      usage: 'Commercial Charging',
    },
    includes: ['เครื่องชาร์จ DC 60 kW', 'หัวชาร์จ CCS2', 'รับประกัน 12 เดือน'],
    features: [
      'Rapid charging',
      'Output split power',
      'ระบบป้องกันอัจฉริยะครบชุด',
      'Emergency stop',
    ],
    financials: null,
    targetSites: ['commercial', 'mall', 'depot'],
    sortOrder: 60,
  },
  {
    id: 'pkg-dc-30-uni',
    slug: 'dc-unicharger-30kw',
    code: 'DC-UNI-30',
    name: 'UNICHARGER Series OC 30 kW',
    nameTh: 'UNICHARGER 30 kW + OneCharge',
    productType: 'equipment',
    sourceLabel: 'EV Infinity · UNICHARGER Series OC',
    tagline: 'DC 30 kW · RFID/QR · OneCharge payment',
    description:
      'เครื่องชาร์จ DC 30 kW พร้อมระบบชำระเงิน OneCharge เหมาะกับโรงแรม ร้านอาหาร โรงงาน และธุรกิจขนาดเล็ก',
    powerKwMin: 30,
    powerKwMax: 30,
    chargerCount: 1,
    nozzleCountMin: 1,
    nozzleCountMax: 1,
    parkingBays: 1,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: 179000,
    pricePromo: 179000,
    priceCapex: null,
    priceNote: 'ราคาเครื่องอ้างอิง · รวมระบบ OneCharge ตามแพ็กผู้จำหน่าย',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      model: 'UNICHARGER Series OC',
      powerKw: 30,
      auth: 'RFID + QR',
      payment: 'OneCharge Scan to Pay',
      display: 'Yes',
    },
    includes: [
      'เครื่องชาร์จ DC 30 kW',
      'ระบบ OneCharge / Scan to Pay',
      'จอแสดงผล',
      'RFID / QR',
    ],
    features: [
      'ชาร์จเร็วสูงสุด 30 kW',
      'มาตรฐานความปลอดภัย',
      'ใช้งานง่ายมีจอแสดงผล',
      'รองรับโรงแรม ร้านอาหาร โรงงาน SME',
    ],
    financials: null,
    targetSites: ['hotel', 'restaurant', 'factory', 'sme'],
    sortOrder: 70,
  },
]
