/**
 * CX ENERTECH official EV package catalog seed.
 * Naming: CX Station + CX DC (S/J) + CX AC — bilingual TH/EN
 * Equipment sell prices from charger-price-rates.ts sellPrice
 * Specs mapped from ZeedaDirect / ZEC / AC datasheets
 */

export type SeedPackage = {
  id: string
  slug: string
  code: string
  name: string
  nameTh: string
  productType: 'equipment' | 'turnkey' | 'investment'
  sourceLabel: string
  tagline: string
  description: string
  powerKwMin: number
  powerKwMax: number
  chargerCount: number | null
  nozzleCountMin: number
  nozzleCountMax: number
  parkingBays: number | null
  transformerKva: number | null
  footprintWm: number | null
  footprintDm: number | null
  priceList: number | null
  pricePromo: number | null
  priceCapex: number | null
  priceNote: string
  roiAnnualPct: number | null
  paybackMonths: number | null
  /** Optional; derived as paybackMonths / 12 when seeding */
  paybackYears?: number | null
  netProfitMonthly: number | null
  specs: Record<string, string | number>
  includes: string[]
  features: string[]
  financials: Record<string, string | number> | null
  targetSites: string[]
  sortOrder: number
  /** Optional card/detail image path under /public */
  image?: string | null
  /** Link to charger-price-rates.ts */
  priceRateId?: string | null
  /** Link to charger-specs.ts */
  specId?: string | null
  /** AC or DC current type — used for catalog filters */
  chargeType?: 'AC' | 'DC' | null
}

export const EV_PACKAGE_SEED: SeedPackage[] = [
  // —— SME Investment (small stations) ——
  {
    id: 'pkg-cx-sme-ac2',
    slug: 'cx-station-sme-ac2',
    code: 'CX-SME-AC2',
    name: 'CX Station SME AC2',
    nameTh: 'สถานีลงทุน SME AC2',
    productType: 'investment',
    sourceLabel: 'CX ENERTECH · SME Investment Series (AC)',
    tagline: '2× AC 22 kW · 2 จุดชาร์จ · ลงทุนเริ่มต้นสำหรับ SME / Entry AC investment',
    description:
      'Small AC destination station for cafés, clinics, offices, and SME parking — สถานี AC ขนาดเล็ก 2 จุด เหมาะกับที่จอดลูกค้าธุรกิจ SME ติดตั้งเร็ว ต้นทุนต่ำ',
    powerKwMin: 44,
    powerKwMax: 44,
    chargerCount: 2,
    nozzleCountMin: 2,
    nozzleCountMax: 2,
    parkingBays: 2,
    transformerKva: null,
    footprintWm: 6,
    footprintDm: 5,
    priceList: null,
    pricePromo: null,
    priceCapex: 320000,
    priceNote:
      'CAPEX อ้างอิงรวมเครื่อง AC 22 kW ×2 ติดตั้ง เสา/ผนัง ป้าย และ commissioning (ยังไม่รวมค่าไฟเข้าใหม่หากจำเป็น)',
    roiAnnualPct: 68.4,
    paybackMonths: 17.5,
    paybackYears: 1.5,
    netProfitMonthly: 18250,
    specs: {
      chargers: '2 × AC E-Series 22 kW (3P)',
      nozzles: '2',
      totalPowerKw: 44,
      electrical: 'MDB 3P · ใช้ไฟฟ้าอาคาร / ไม่ต้องมีหม้อแปลงแยก',
      footprint: '≈ 6.0 × 5.0 m (2 ช่องจอด)',
      auth: 'RFID / App / OCPP',
    },
    includes: [
      'เครื่องชาร์จ AC 22 kW จำนวน 2 เครื่อง',
      'ติดตั้ง wall/pedestal · สายไฟ · breaker',
      'งานจุดจอด EV 2 ช่อง · ป้ายสถานี',
      'Internet / OCPP backend พื้นฐาน',
      'ทดสอบและ commissioning',
    ],
    features: [
      'CAPEX ต่ำ เริ่มลงทุนได้เร็ว',
      'เหมาะกับลูกค้าจอดนาน (โรงแรม คาเฟ่ ออฟฟิศ)',
      'ไม่ต้องมีหม้อแปลงแยกในเคสทั่วไป',
      'โมเดลรายได้อ้างอิงสำหรับ SME',
    ],
    financials: {
      operatingHoursPerDay: 10,
      utilizationPct: 35,
      kwhPerDay: 154,
      kwhPerMonth: 4620,
      sellPricePerKwh: 7.5,
      energyCostPerKwh: 2.8,
      revenueMonthly: 34650,
      energyCostMonthly: 12936,
      platformFeePct: 10,
      investorPct: 100,
      investorNetMonthly: 18250,
      annualNet: 219000,
      roiAnnualPct: 68.4,
      paybackMonths: 17.5,
      paybackYears: 1.5,
    },
    targetSites: ['sme', 'cafe', 'clinic', 'office', 'hotel'],
    sortOrder: 1,
    image: '/images/packages/cx-sme-ac2.jpg',
    chargeType: 'AC',
  },
  {
    id: 'pkg-cx-sme-ac4',
    slug: 'cx-station-sme-ac4',
    code: 'CX-SME-AC4',
    name: 'CX Station SME AC4',
    nameTh: 'สถานีลงทุน SME AC4',
    productType: 'investment',
    sourceLabel: 'CX ENERTECH · SME Investment Series (AC)',
    tagline: '4× AC 22 kW · 4 จุดชาร์จ · ที่จอดลูกค้า / ชุมชน / คอนโดขนาดเล็ก',
    description:
      '4-bay AC station for SME compounds, small condo, and customer parking — สถานี AC 4 จุด สำหรับหมู่บ้านจัดสรร ออฟฟิศ และที่จอดลูกค้า',
    powerKwMin: 88,
    powerKwMax: 88,
    chargerCount: 4,
    nozzleCountMin: 4,
    nozzleCountMax: 4,
    parkingBays: 4,
    transformerKva: null,
    footprintWm: 12,
    footprintDm: 5.5,
    priceList: null,
    pricePromo: null,
    priceCapex: 520000,
    priceNote:
      'CAPEX อ้างอิงรวมเครื่อง AC 22 kW ×4 ติดตั้ง งานจุดจอด ป้าย และ commissioning',
    roiAnnualPct: 84.2,
    paybackMonths: 14.2,
    paybackYears: 1.2,
    netProfitMonthly: 36500,
    specs: {
      chargers: '4 × AC E-Series 22 kW (3P)',
      nozzles: '4',
      totalPowerKw: 88,
      electrical: 'MDB 3P · load management แนะนำ',
      footprint: '≈ 12.0 × 5.5 m (4 ช่องจอด)',
      auth: 'RFID / App / OCPP',
    },
    includes: [
      'เครื่องชาร์จ AC 22 kW จำนวน 4 เครื่อง',
      'ติดตั้ง wall/pedestal · MDB ย่อย · load balance พื้นฐาน',
      'งานจุดจอด EV 4 ช่อง · ป้ายสถานี',
      'Internet / OCPP backend',
      'ทดสอบและ commissioning',
    ],
    features: [
      'รองรับลูกค้าหลายคันพร้อมกัน',
      'เหมาะกับคอนโดขนาดเล็ก / ออฟฟิศ / ร้านค้า',
      'ขยายจาก AC2 ได้',
      'ROI อ้างอิงสูงกว่าแพ็กเกจ AC2',
    ],
    financials: {
      operatingHoursPerDay: 10,
      utilizationPct: 35,
      kwhPerDay: 308,
      kwhPerMonth: 9240,
      sellPricePerKwh: 7.5,
      energyCostPerKwh: 2.8,
      revenueMonthly: 69300,
      energyCostMonthly: 25872,
      platformFeePct: 10,
      investorPct: 100,
      investorNetMonthly: 36500,
      annualNet: 438000,
      roiAnnualPct: 84.2,
      paybackMonths: 14.2,
      paybackYears: 1.2,
    },
    targetSites: ['sme', 'condo', 'office', 'community', 'hotel'],
    sortOrder: 2,
    image: '/images/packages/cx-sme-ac4.jpg',
    chargeType: 'AC',
  },
  {
    id: 'pkg-cx-sme-dc30',
    slug: 'cx-station-sme-dc30',
    code: 'CX-SME-DC30',
    name: 'CX Station SME DC30',
    nameTh: 'สถานีลงทุน SME DC30',
    productType: 'investment',
    sourceLabel: 'CX ENERTECH · SME Investment Series (DC)',
    tagline: '1× DC 30 kW · 1 หัวชาร์จ · ลงทุนเริ่มต้น DC สำหรับ SME',
    description:
      'Entry DC fast-charge package for cafés, clinics, and small retail — สถานี DC 30 kW 1 ตู้ เหมาะกับธุรกิจ SME ที่อยากเริ่มชาร์จเร็วด้วยงบจำกัด',
    powerKwMin: 30,
    powerKwMax: 30,
    chargerCount: 1,
    nozzleCountMin: 1,
    nozzleCountMax: 1,
    parkingBays: 1,
    transformerKva: null,
    footprintWm: 6,
    footprintDm: 5,
    priceList: null,
    pricePromo: null,
    priceCapex: 520000,
    priceNote:
      'CAPEX อ้างอิงรวมเครื่อง DC 30 kW (J1) ติดตั้งไฟฟ้า งานจุดจอด ป้าย และ commissioning',
    roiAnnualPct: 38.7,
    paybackMonths: 31,
    paybackYears: 2.6,
    netProfitMonthly: 16790,
    specs: {
      chargers: '1 × DC J1 30 kW (single gun)',
      nozzles: '1',
      totalPowerKw: 30,
      electrical: 'MDB 3P · ใช้ไฟฟ้าอาคาร / ประเมินหม้อแปลงก่อนติดตั้ง',
      footprint: '≈ 6.0 × 5.0 m (1 ช่องจอด)',
      auth: 'RFID / App / OCPP 1.6J',
    },
    includes: [
      'เครื่องชาร์จ DC 30 kW 1 ตู้',
      'งานไฟฟ้า · breaker · ติดตั้งและ grounding',
      'งานจุดจอด EV 1 ช่อง · ป้ายสถานี',
      'Internet / OCPP backend',
      'ทดสอบและ commissioning',
    ],
    features: [
      'งบเริ่มต้นต่ำสุดในไลน์ DC SME',
      'เหมาะกับคาเฟ่ / คลินิก / ร้านค้า',
      'ขยายไป DC40 / DC60 ได้',
      'โมเดลลงทุนพร้อมประมาณการรายได้',
    ],
    financials: {
      operatingHoursPerDay: 8,
      utilizationPct: 55,
      kwhPerDay: 132,
      kwhPerMonth: 3960,
      sellPricePerKwh: 8,
      energyCostPerKwh: 2.8,
      revenueMonthly: 31680,
      energyCostMonthly: 11088,
      platformFeePct: 12,
      investorPct: 100,
      investorNetMonthly: 16790,
      annualNet: 201480,
      roiAnnualPct: 38.7,
      paybackMonths: 31,
      paybackYears: 2.6,
    },
    targetSites: ['sme', 'cafe', 'clinic', 'retail', 'hotel'],
    sortOrder: 3,
    image: '/images/packages/cx-sme-dc30.jpg',
    specId: 'spec-zd-j1',
  },
  {
    id: 'pkg-cx-sme-dc40',
    slug: 'cx-station-sme-dc40',
    code: 'CX-SME-DC40',
    name: 'CX Station SME DC40',
    nameTh: 'สถานีลงทุน SME DC40',
    productType: 'investment',
    sourceLabel: 'CX ENERTECH · SME Investment Series (DC)',
    tagline: '1× DC 40 kW · 2 หัวชาร์จ · จุดแวะชาร์จเร็วขนาดเล็ก',
    description:
      'Compact dual-gun DC station on J2 40 kW — สถานี DC 40 kW 1 ตู้ 2 หัว สำหรับร้านอาหาร เวิร์กช็อป และที่จอดลูกค้า SME',
    powerKwMin: 40,
    powerKwMax: 40,
    chargerCount: 1,
    nozzleCountMin: 2,
    nozzleCountMax: 2,
    parkingBays: 2,
    transformerKva: null,
    footprintWm: 7,
    footprintDm: 5.5,
    priceList: null,
    pricePromo: null,
    priceCapex: 680000,
    priceNote:
      'CAPEX อ้างอิงรวมเครื่อง DC 40 kW (J2) ติดตั้งไฟฟ้า งานจุดจอด ป้าย และ commissioning',
    roiAnnualPct: 41.8,
    paybackMonths: 28.7,
    paybackYears: 2.4,
    netProfitMonthly: 23659,
    specs: {
      chargers: '1 × DC J2 40 kW (dual gun)',
      nozzles: '2',
      totalPowerKw: 40,
      electrical: 'MDB 3P · ประเมินหม้อแปลงอาคารก่อนติดตั้ง',
      footprint: '≈ 7.0 × 5.5 m (2 ช่องจอด)',
      auth: 'RFID / App / OCPP 1.6J',
    },
    includes: [
      'เครื่องชาร์จ DC 40 kW 1 ตู้ (dual connector)',
      'งานไฟฟ้า · breaker · ติดตั้งและ grounding',
      'งานจุดจอด EV 2 ช่อง · ป้ายสถานี',
      'Internet / OCPP backend',
      'ทดสอบและ commissioning',
    ],
    features: [
      '2 หัวชาร์จในตู้เดียว',
      'ก้าวกลางระหว่าง DC30 และ DC60',
      'เหมาะกับหน้าร้าน / ปั๊มเล็ก',
      'แพลตฟอร์ม J2 ขยายกำลังได้',
    ],
    financials: {
      operatingHoursPerDay: 8,
      utilizationPct: 58,
      kwhPerDay: 186,
      kwhPerMonth: 5580,
      sellPricePerKwh: 8,
      energyCostPerKwh: 2.8,
      revenueMonthly: 44640,
      energyCostMonthly: 15624,
      platformFeePct: 12,
      investorPct: 100,
      investorNetMonthly: 23659,
      annualNet: 283908,
      roiAnnualPct: 41.8,
      paybackMonths: 28.7,
      paybackYears: 2.4,
    },
    targetSites: ['sme', 'restaurant', 'workshop', 'retail', 'gas'],
    sortOrder: 4,
    image: '/images/packages/cx-sme-dc40.jpg',
    specId: 'spec-zd-j2',
  },
  {
    id: 'pkg-cx-sme-dc1',
    slug: 'cx-station-sme-dc60',
    code: 'CX-SME-DC60',
    name: 'CX Station SME DC60',
    nameTh: 'สถานีลงทุน SME DC60',
    productType: 'investment',
    sourceLabel: 'CX ENERTECH · SME Investment Series (DC)',
    tagline: '1× DC 60 kW · 2 หัวชาร์จ · จุดแวะชาร์จเร็วสำหรับ SME',
    description:
      'Compact DC fast-charge corner for restaurants, workshops, and small retail — สถานี DC 60 kW ขนาดกะทัดรัด 2 หัว สำหรับธุรกิจที่ต้องการชาร์จเร็ว',
    powerKwMin: 60,
    powerKwMax: 60,
    chargerCount: 1,
    nozzleCountMin: 2,
    nozzleCountMax: 2,
    parkingBays: 2,
    transformerKva: null,
    footprintWm: 8,
    footprintDm: 6,
    priceList: null,
    pricePromo: null,
    priceCapex: 890000,
    priceNote:
      'CAPEX อ้างอิงรวมเครื่อง DC 60 kW (J-Series) ติดตั้งไฟฟ้า งานจุดจอด ป้าย และ commissioning',
    roiAnnualPct: 49.4,
    paybackMonths: 24.3,
    paybackYears: 2.0,
    netProfitMonthly: 36630,
    specs: {
      chargers: '1 × DC J-Series 60 kW (dual gun)',
      nozzles: '2',
      totalPowerKw: 60,
      electrical: 'MDB 3P · ประเมินหม้อแปลงอาคารก่อนติดตั้ง',
      footprint: '≈ 8.0 × 6.0 m (2 ช่องจอด)',
      auth: 'RFID / App / OCPP 1.6J',
    },
    includes: [
      'เครื่องชาร์จ DC 60 kW 1 ตู้ (dual connector)',
      'งานไฟฟ้า · breaker · ติดตั้งและ grounding',
      'งานจุดจอด EV 2 ช่อง · ป้ายสถานี',
      'Internet / OCPP backend',
      'ทดสอบและ commissioning',
    ],
    features: [
      'ชาร์จเร็วกว่าระบบ AC ชัดเจน',
      'ใช้พื้นที่น้อย เหมาะกับหน้าร้าน / ปั๊มเล็ก',
      'ราคาอุปกรณ์อ้างอิงจากตาราง J-Series',
      'โมเดลลงทุน SME ไม่ต้องลงสถานีใหญ่',
    ],
    financials: {
      operatingHoursPerDay: 8,
      utilizationPct: 60,
      kwhPerDay: 288,
      kwhPerMonth: 8640,
      sellPricePerKwh: 8,
      energyCostPerKwh: 2.8,
      revenueMonthly: 69120,
      energyCostMonthly: 24192,
      platformFeePct: 12,
      investorPct: 100,
      investorNetMonthly: 36630,
      annualNet: 439560,
      roiAnnualPct: 49.4,
      paybackMonths: 24.3,
      paybackYears: 2.0,
    },
    targetSites: ['sme', 'restaurant', 'workshop', 'retail', 'gas'],
    sortOrder: 5,
    image: '/images/packages/cx-sme-dc1.jpg',
    priceRateId: 'rate-dc-j-60',
    specId: 'spec-zd-j1',
  },
  {
    id: 'pkg-cx-sme-dc2',
    slug: 'cx-station-sme-dc120',
    code: 'CX-SME-DC120',
    name: 'CX Station SME DC120',
    nameTh: 'สถานีลงทุน SME DC120',
    productType: 'investment',
    sourceLabel: 'CX ENERTECH · SME Investment Series (DC)',
    tagline: '1× DC 120 kW · 2 หัวชาร์จ · ขยายทราฟฟิก SME / คลังเล็ก',
    description:
      'Higher-throughput SME DC station for busy retail, small depot, and roadside sites — สถานี DC 120 kW สำหรับธุรกิจทราฟฟิกสูงขึ้นโดยยังเป็นสเกล SME',
    powerKwMin: 120,
    powerKwMax: 120,
    chargerCount: 1,
    nozzleCountMin: 2,
    nozzleCountMax: 2,
    parkingBays: 2,
    transformerKva: 250,
    footprintWm: 9,
    footprintDm: 6.5,
    priceList: null,
    pricePromo: null,
    priceCapex: 1550000,
    priceNote:
      'CAPEX อ้างอิงรวมเครื่อง DC 120 kW (J-Series) ราคาต่อหน่วย 1,550,000 บาท ไฟฟ้า/หม้อแปลงขนาดเล็ก งานจุดจอด และ commissioning',
    roiAnnualPct: 52,
    paybackMonths: 23.1,
    paybackYears: 1.9,
    netProfitMonthly: 67162,
    specs: {
      chargers: '1 × DC J-Series 120 kW (dual gun)',
      nozzles: '2',
      totalPowerKw: 120,
      electrical: 'Transformer ~250 kVA หรือใช้ไฟฟ้าอาคารที่รองรับได้',
      footprint: '≈ 9.0 × 6.5 m (2 ช่องจอด)',
      auth: 'RFID / App / OCPP 1.6J',
    },
    includes: [
      'เครื่องชาร์จ DC 120 kW 1 ตู้ (dual connector)',
      'งานไฟฟ้า · MDB · Transformer ขนาดเล็ก (ตามไซต์)',
      'งานจุดจอด EV 2 ช่อง · ป้ายสถานี',
      'Internet / OCPP backend',
      'CCTV 2 กล้อง (ออปชันแนะนำ)',
      'ทดสอบและ commissioning',
    ],
    features: [
      'กำลังไฟสูงกว่ารุ่น DC60 ประมาณ 2 เท่า',
      'เหมาะกับคลังเล็ก / ปั๊ม / ร้านค้าทราฟฟิกสูง',
      'ยังเล็กกว่า CX Station S4 ชัดเจน',
      'ราคาอุปกรณ์อ้างอิงจากตาราง J-Series',
    ],
    financials: {
      operatingHoursPerDay: 8,
      utilizationPct: 55,
      kwhPerDay: 528,
      kwhPerMonth: 15840,
      sellPricePerKwh: 8,
      energyCostPerKwh: 2.8,
      revenueMonthly: 126720,
      energyCostMonthly: 44352,
      platformFeePct: 12,
      investorPct: 100,
      investorNetMonthly: 67162,
      annualNet: 805944,
      roiAnnualPct: 52,
      paybackMonths: 23.1,
      paybackYears: 1.9,
    },
    targetSites: ['sme', 'depot', 'retail', 'gas', 'workshop'],
    sortOrder: 6,
    image: '/images/packages/cx-sme-dc2.jpg',
    priceRateId: 'rate-dc-j-120',
    specId: 'spec-zd-j2',
  },
  {
    id: 'pkg-cx-sme-dc180',
    slug: 'cx-station-sme-dc180',
    code: 'CX-SME-DC180',
    name: 'CX Station SME DC180',
    nameTh: 'สถานีลงทุน SME DC180',
    productType: 'investment',
    sourceLabel: 'CX ENERTECH · SME Investment Series (DC)',
    tagline: '1× DC 180 kW · 2 หัวชาร์จ · สถานีเร็วระดับกลางสำหรับ SME',
    description:
      'Mid-power SME DC station on ZeedaDirect J3 (160/180/240) — สถานี DC 180 kW สำหรับปั๊มเล็ก คลัง และจุดแวะชาร์จทราฟฟิกปานกลาง-สูง',
    powerKwMin: 180,
    powerKwMax: 180,
    chargerCount: 1,
    nozzleCountMin: 2,
    nozzleCountMax: 2,
    parkingBays: 2,
    transformerKva: 315,
    footprintWm: 10,
    footprintDm: 7,
    priceList: null,
    pricePromo: null,
    priceCapex: 1950000,
    priceNote:
      'CAPEX อ้างอิงรวมเครื่อง DC 180 kW (J3) ไฟฟ้า/หม้อแปลง งานจุดจอด และ commissioning · รออัปเดตราคาเครื่องในตาราง J-Series',
    roiAnnualPct: 54.1,
    paybackMonths: 22.2,
    paybackYears: 1.8,
    netProfitMonthly: 87920,
    specs: {
      chargers: '1 × DC J-Series / ZD-DC-J3 180 kW (dual gun)',
      nozzles: '2',
      totalPowerKw: 180,
      electrical: 'Transformer ~315 kVA + MDB',
      footprint: '≈ 10.0 × 7.0 m (2 ช่องจอด)',
      auth: 'RFID / App / OCPP 1.6J',
      maxCurrent: 'CCS2 up to 250A',
    },
    includes: [
      'เครื่องชาร์จ DC 180 kW 1 ตู้ (dual connector)',
      'งานไฟฟ้า · MDB · Transformer ~315 kVA (ตามไซต์)',
      'งานจุดจอด EV 2 ช่อง · ป้ายสถานี',
      'Internet / OCPP backend',
      'CCTV 2 กล้อง',
      'ทดสอบและ commissioning',
    ],
    features: [
      'ชาร์จเร็วระดับสถานีกลาง โดยสเกลยังเป็น SME',
      'แพลตฟอร์ม J3 (160/180/240 kW)',
      'เล็กกว่า CX Station S4 (2×120 kW)',
      'เหมาะกับปั๊ม / คลัง / จุดแวะทางหลวงรอง',
    ],
    financials: {
      operatingHoursPerDay: 8,
      utilizationPct: 48,
      kwhPerDay: 691,
      kwhPerMonth: 20736,
      sellPricePerKwh: 8,
      energyCostPerKwh: 2.8,
      revenueMonthly: 165888,
      energyCostMonthly: 58061,
      platformFeePct: 12,
      investorPct: 100,
      investorNetMonthly: 87920,
      annualNet: 1055040,
      roiAnnualPct: 54.1,
      paybackMonths: 22.2,
      paybackYears: 1.8,
    },
    targetSites: ['sme', 'gas', 'depot', 'highway', 'retail'],
    sortOrder: 7,
    image: '/images/packages/cx-sme-dc180.jpg',
    priceRateId: 'rate-dc-j-180',
    specId: 'spec-zd-j3',
  },
  {
    id: 'pkg-cx-sme-dc240',
    slug: 'cx-station-sme-dc240',
    code: 'CX-SME-DC240',
    name: 'CX Station SME DC240',
    nameTh: 'สถานีลงทุน SME DC240',
    productType: 'investment',
    sourceLabel: 'CX ENERTECH · SME Investment Series (DC)',
    tagline: '1× DC 240 kW · 2 หัวชาร์จ · สูงสุดในไลน์ SME ก่อนขึ้น S4',
    description:
      'Top SME DC package on J3/J4 platforms — สถานี DC 240 kW กำลังสูงสุดในซีรีส์ SME ก่อนก้าวไป CX Station S4',
    powerKwMin: 240,
    powerKwMax: 240,
    chargerCount: 1,
    nozzleCountMin: 2,
    nozzleCountMax: 2,
    parkingBays: 2,
    transformerKva: 400,
    footprintWm: 10,
    footprintDm: 7.5,
    priceList: null,
    pricePromo: null,
    priceCapex: 2350000,
    priceNote:
      'CAPEX อ้างอิงรวมเครื่อง DC 240 kW (J3/J4) ไฟฟ้า/หม้อแปลง งานจุดจอด และ commissioning · รออัปเดตราคาเครื่องในตาราง J-Series',
    roiAnnualPct: 59.9,
    paybackMonths: 20.0,
    paybackYears: 1.7,
    netProfitMonthly: 117230,
    specs: {
      chargers: '1 × DC J-Series / ZD-DC-J3·J4 240 kW (dual gun)',
      nozzles: '2',
      totalPowerKw: 240,
      electrical: 'Transformer ~400 kVA + MDB',
      footprint: '≈ 10.0 × 7.5 m (2 ช่องจอด)',
      auth: 'RFID / App / OCPP 1.6J',
      maxCurrent: 'CCS2 up to 400A',
    },
    includes: [
      'เครื่องชาร์จ DC 240 kW 1 ตู้ (dual connector)',
      'งานไฟฟ้า · MDB · Transformer ~400 kVA (ตามไซต์)',
      'งานจุดจอด EV 2 ช่อง · ป้ายสถานี',
      'Internet / OCPP backend',
      'CCTV 2–4 กล้อง',
      'ทดสอบและ commissioning',
    ],
    features: [
      'กำลังรวมเทียบเคียง 1 ตู้ของสถานีใหญ่',
      'รองรับรถ 800V / ชาร์จเร็วสูง',
      'แพลตฟอร์ม J3 หรือ J4 ตามไซต์',
      'ทางเลือกก่อนลงทุน CX Station S4',
    ],
    financials: {
      operatingHoursPerDay: 8,
      utilizationPct: 48,
      kwhPerDay: 922,
      kwhPerMonth: 27648,
      sellPricePerKwh: 8,
      energyCostPerKwh: 2.8,
      revenueMonthly: 221184,
      energyCostMonthly: 77414,
      platformFeePct: 12,
      investorPct: 100,
      investorNetMonthly: 117230,
      annualNet: 1406760,
      roiAnnualPct: 59.9,
      paybackMonths: 20.0,
      paybackYears: 1.7,
    },
    targetSites: ['sme', 'gas', 'depot', 'highway', 'hub'],
    sortOrder: 8,
    image: '/images/packages/cx-sme-dc240.jpg',
    priceRateId: 'rate-dc-j-240',
    specId: 'spec-zd-j4',
  },
  {
    id: 'pkg-cx-s4',
    slug: 'cx-station-s4',
    code: 'CX-S4',
    name: 'CX Station S4',
    nameTh: 'สถานีชาร์จ CX Station S4',
    productType: 'turnkey',
    sourceLabel: 'CX ENERTECH · Station Investment Series',
    tagline: '4 หัวจ่าย · 2× DC 120 kW · 4 charging bays · Ready-to-run investment / แพ็กเกจลงทุนพร้อมใช้งาน',
    description:
      'Entry-size CX ENERTECH charging station with chargers, electrical works, canopy, CCTV, and investor revenue model — แพ็กเกจสถานีขนาดเริ่มต้น ครบเครื่องชาร์จ ระบบไฟฟ้า โครงสร้างหลังคา กล้องวงจรปิด และโมเดลรายได้',
    powerKwMin: 240,
    powerKwMax: 240,
    chargerCount: 2,
    nozzleCountMin: 4,
    nozzleCountMax: 4,
    parkingBays: 4,
    transformerKva: 400,
    footprintWm: 12,
    footprintDm: 6.5,
    priceList: null,
    pricePromo: null,
    priceCapex: 3670000,
    priceNote:
      'CAPEX อ้างอิงรวมอุปกรณ์ ติดตั้ง และ commissioning (เครื่อง DC 120 kW ×2 ราคาต่อหน่วย 1,550,000 บาท)',
    roiAnnualPct: 74.9,
    paybackMonths: 16,
    paybackYears: 1.3,
    netProfitMonthly: 228960,
    specs: {
      chargers: '2 × DC Fast Charger 120 kW',
      nozzles: '4 (2 ต่อเครื่อง)',
      totalPowerKw: 240,
      electrical: '240 kVA / MDB + Transformer 400 kVA',
      footprint: '12.0 × 6.5 m',
      cctv: '4 กล้อง + NVR',
    },
    includes: [
      'เครื่องชาร์จ DC 120 kW จำนวน 2 ตู้',
      'ระบบไฟฟ้าแรงสูง/ต่ำ · MDB · Transformer 400 kVA',
      'โครงสร้างหลังคา / canopy',
      'งานจุดจอด EV 4 ช่อง · landscaping · ป้ายสถานี',
      'ระบบสื่อสาร / Internet',
      'CCTV 4 กล้อง + NVR',
      'ทดสอบและ commissioning',
    ],
    features: [
      'มาตรฐานความปลอดภัย',
      'ชาร์จเร็ว เสถียร',
      'เหมาะกับพื้นที่เริ่มต้น',
      'พร้อมโมเดลลงทุนและประมาณการรายได้',
    ],
    financials: {
      operatingHoursPerDay: 10,
      kwhPerDay: 2400,
      kwhPerMonth: 72000,
      sellPricePerKwh: 8,
      energyCostPerKwh: 2.8,
      revenueMonthly: 576000,
      platformFeePct: 12,
      gpSharePct: 25,
      coordinatorPct: 10,
      investorPct: 90,
      investorNetMonthly: 228960,
      annualNet: 2747520,
      roiAnnualPct: 74.9,
      paybackMonths: 16,
      paybackYears: 1.3,
    },
    targetSites: ['commercial', 'sme', 'office', 'factory'],
    sortOrder: 10,
    image: '/images/packages/cx-station-s4.jpg',
  },
  // {
  //   id: 'pkg-cx-s10',
  //   slug: 'cx-station-s10',
  //   code: 'CX-S10',
  //   name: 'CX Station S10',
  //   nameTh: 'สถานีชาร์จ CX Station S10',
  //   productType: 'turnkey',
  //   sourceLabel: 'CX ENERTECH · Station Investment Series',
  //   tagline: '10 หัวจ่าย · 5× DC 120 kW · 10 bays · 600 kW total / สถานีทราฟฟิกสูง',
  //   description:
  //     'Mid-to-large station for high-traffic sites with full structure, electrical works, and landowner revenue share — สถานีขนาดกลาง-ใหญ่ ครบโครงสร้าง ไฟฟ้า และโมเดลแบ่งรายได้กับเจ้าของที่ดิน',
  //   powerKwMin: 600,
  //   powerKwMax: 600,
  //   chargerCount: 5,
  //   nozzleCountMin: 10,
  //   nozzleCountMax: 10,
  //   parkingBays: 10,
  //   transformerKva: 1000,
  //   footprintWm: 30,
  //   footprintDm: 7.5,
  //   priceList: null,
  //   pricePromo: null,
  //   priceCapex: 9000000,
  //   priceNote: 'CAPEX อ้างอิงรวมอุปกรณ์ ติดตั้ง และ commissioning',
  //   roiAnnualPct: 67.2,
  //   paybackMonths: 17.9,
  //   paybackYears: 1.5,
  //   netProfitMonthly: 453600,
  //   specs: {
  //     chargers: '5 × DC Fast Charger 120 kW',
  //     nozzles: '10 (2 ต่อเครื่อง)',
  //     totalPowerKw: 600,
  //     electrical: 'Transformer 1,000 kVA + MDB',
  //     footprint: '30.0 × 7.5 m',
  //     cctv: '4 กล้อง + NVR',
  //   },
  //   includes: [
  //     'เครื่องชาร์จ DC 120 kW จำนวน 5 ตู้',
  //     'ระบบไฟฟ้าแรงสูง · Transformer 1,000 kVA · MDB',
  //     'โครงสร้างหลังคา / canopy',
  //     'งานจุดจอด EV 10 ช่อง · landscaping',
  //     'ป้ายสถานี CX ENERTECH',
  //     'ระบบสื่อสาร / Internet',
  //     'CCTV 4 กล้อง + NVR',
  //     'ทดสอบและ commissioning',
  //   ],
  //   features: [
  //     'รองรับทราฟฟิกสูง',
  //     'Layout สถานีมาตรฐาน',
  //     'โมเดลแบ่งรายได้เจ้าของที่ดิน',
  //     'เหมาะกับห้าง ปั๊ม และแหล่งท่องเที่ยว',
  //   ],
  //   financials: {
  //     operatingHoursPerDay: 10,
  //     kwhPerDay: 6000,
  //     kwhPerMonth: 180000,
  //     sellPricePerKwh: 8,
  //     energyCostPerKwh: 2.8,
  //     revenueMonthly: 1440000,
  //     landOwnerPctOfRevenue: 15,
  //     platformFeePct: 15,
  //     coordinatorPct: 10,
  //     investorPct: 90,
  //     investorNetMonthly: 453600,
  //     annualNet: 6048000,
  //     roiAnnualPct: 67.2,
  //     paybackMonths: 17.9,
  //     paybackYears: 1.5,
  //   },
  //   targetSites: ['tourism', 'mall', 'gas', 'public'],
  //   sortOrder: 20,
  //   image: '/images/packages/cx-station-s10.jpg',
  // },
  // {
  //   id: 'pkg-cx-hub',
  //   slug: 'cx-station-hub',
  //   code: 'CX-HUB',
  //   name: 'CX Station Hub',
  //   nameTh: '6 หัวจ่ายHub',
  //   productType: 'turnkey',
  //   sourceLabel: 'CX ENERTECH · Hub Series',
  //   tagline: '480–960 kW · 2–12 bays · Scalable hub / ปรับขนาดตามพื้นที่',
  //   description:
  //     'High-capacity Hub package with configurable dispensers for gas stations, malls, hotels, and public parking — แพ็กเกจ Hub ความจุสูง ปรับจำนวนหัวชาร์จตามพื้นที่',
  //   powerKwMin: 480,
  //   powerKwMax: 960,
  //   chargerCount: 1,
  //   nozzleCountMin: 2,
  //   nozzleCountMax: 12,
  //   parkingBays: null,
  //   transformerKva: null,
  //   footprintWm: null,
  //   footprintDm: null,
  //   priceList: null,
  //   pricePromo: 5590000,
  //   priceCapex: 5590000,
  //   priceNote: 'ราคาเริ่มต้นรวม VAT · รวมตู้ชาร์จ Power Cabinet ติดตั้ง และบริการหลังการขาย',
  //   roiAnnualPct: null,
  //   paybackMonths: null,
  //   netProfitMonthly: null,
  //   specs: {
  //     powerRangeKw: '480–960',
  //     nozzles: '2–12 (ปรับได้)',
  //     architecture: 'Power Cabinet + DC Dispenser',
  //     warrantyYears: 2,
  //   },
  //   includes: [
  //     'High-power DC Charger',
  //     'Power Cabinet',
  //     'ติดตั้งและทดสอบระบบ',
  //     'บริการหลังการขาย',
  //     'รับประกัน 2 ปี',
  //   ],
  //   features: [
  //     'ชาร์จหลายคันพร้อมกัน',
  //     'ระบบป้องกันครบ',
  //     'ทำงานต่อเนื่อง 24/7',
  //     'ขยายหัวชาร์จตามพื้นที่',
  //   ],
  //   financials: null,
  //   targetSites: ['gas', 'mall', 'hotel', 'office', 'parking'],
  //   sortOrder: 30,
  //   image: '/images/packages/cx-station-hub.jpg',
  // },
  // —— EV Hub turnkey: 6 / 8 / 10 nozzles × 120 / 180 kW ——
  {
    id: 'pkg-cx-hub-6-120',
    slug: 'cx-hub-6-120',
    code: 'CX-HUB-6-120',
    name: 'CX Hub 6 · 120 kW',
    nameTh: 'สถานีสำเร็จรูป CX Hub 6 หัว · 120 kW',
    productType: 'turnkey',
    sourceLabel: 'CX ENERTECH · EV Hub Turnkey Series',
    tagline: '6 หัวจ่าย · 3× DC 120 kW · กำลังรวม 360 kW / Ready-to-run hub',
    description:
      'Turnkey EV hub with 6 charging nozzles on 120 kW dual-gun cabinets — สถานีสำเร็จรูป 6 หัวจ่าย ใช้เครื่อง DC 120 kW ×3 เหมาะกับปั๊ม ห้าง และที่จอดสาธารณะขนาดกลาง',
    powerKwMin: 360,
    powerKwMax: 360,
    chargerCount: 3,
    nozzleCountMin: 6,
    nozzleCountMax: 6,
    parkingBays: 6,
    transformerKva: 500,
    footprintWm: 16,
    footprintDm: 7,
    priceList: null,
    pricePromo: 4880000,
    priceCapex: 4880000,
    priceNote:
      'ราคาสำเร็จรูปรวมเครื่อง DC 120 kW ×3 (ราคาต่อหน่วย 1,550,000 บาท) ไฟฟ้า/หม้อแปลง canopy จุดจอด และ commissioning (อ้างอิงอุปกรณ์ J-Series 120 kW)',
    roiAnnualPct: 84.5,
    paybackMonths: 14.2,
    paybackYears: 1.2,
    netProfitMonthly: 343440,
    specs: {
      chargers: '3 × DC 120 kW dual gun',
      nozzles: '6 (2 ต่อตู้)',
      totalPowerKw: 360,
      architecture: 'Integrated DC cabinets + canopy',
      electrical: 'Transformer 500 kVA + MDB',
      footprint: '≈ 16 × 7 m',
      warrantyYears: 2,
    },
    includes: [
      'เครื่องชาร์จ DC 120 kW จำนวน 3 ตู้ (6 หัว)',
      'Transformer ~500 kVA · MDB · งานไฟฟ้า',
      'โครงสร้างหลังคา / canopy',
      'งานจุดจอด EV 6 ช่อง · ป้ายสถานี',
      'Internet / OCPP · CCTV พื้นฐาน',
      'ติดตั้ง ทดสอบ และรับประกัน 2 ปี',
    ],
    features: [
      'จำนวนหัวจ่ายคงที่ 6 หัว พร้อมส่งมอบ',
      'ใช้เครื่อง 120 kW มาตรฐานสถานี',
      'เหมาะกับปั๊ม / ห้างขนาดกลาง',
      'ขยายไป Hub 8/10 ได้',
    ],
    financials: {
      operatingHoursPerDay: 10,
      kwhPerDay: 3600,
      kwhPerMonth: 108000,
      sellPricePerKwh: 8,
      energyCostPerKwh: 2.8,
      revenueMonthly: 864000,
      platformFeePct: 12,
      gpSharePct: 25,
      coordinatorPct: 10,
      investorPct: 90,
      investorNetMonthly: 343440,
      annualNet: 4121280,
      roiAnnualPct: 84.5,
      paybackMonths: 14.2,
      paybackYears: 1.2,
    },
    targetSites: ['gas', 'mall', 'parking', 'hotel', 'public'],
    sortOrder: 31,
    image: '/images/packages/cx-hub-6-120.jpg',
    priceRateId: 'rate-dc-j-120',
    specId: 'spec-zd-j2',
  },
  {
    id: 'pkg-cx-hub-6-180',
    slug: 'cx-hub-6-180',
    code: 'CX-HUB-6-180',
    name: 'CX Hub 6 · 180 kW',
    nameTh: 'สถานีสำเร็จรูป CX Hub 6 หัว · 180 kW',
    productType: 'turnkey',
    sourceLabel: 'CX ENERTECH · EV Hub Turnkey Series',
    tagline: '6 หัวจ่าย · 3× DC 180 kW · กำลังรวม 540 kW / Fast hub',
    description:
      'Turnkey EV hub with 6 nozzles on 180 kW dual-gun cabinets — สถานีสำเร็จรูป 6 หัว ใช้เครื่อง DC 180 kW ×3 ชาร์จเร็วขึ้นในพื้นที่เท่ากัน',
    powerKwMin: 540,
    powerKwMax: 540,
    chargerCount: 3,
    nozzleCountMin: 6,
    nozzleCountMax: 6,
    parkingBays: 6,
    transformerKva: 800,
    footprintWm: 16,
    footprintDm: 7,
    priceList: null,
    pricePromo: 5850000,
    priceCapex: 5850000,
    priceNote:
      'ราคาสำเร็จรูปรวมเครื่อง DC 180 kW ×3 ไฟฟ้า/หม้อแปลง canopy จุดจอด และ commissioning (ราคาเครื่อง 180 kW อ้างอิงประมาณการ)',
    roiAnnualPct: 105.7,
    paybackMonths: 11.4,
    paybackYears: 1.0,
    netProfitMonthly: 515160,
    specs: {
      chargers: '3 × DC 180 kW dual gun',
      nozzles: '6 (2 ต่อตู้)',
      totalPowerKw: 540,
      architecture: 'Integrated DC cabinets + canopy (J3 platform)',
      electrical: 'Transformer 800 kVA + MDB',
      footprint: '≈ 16 × 7 m',
      warrantyYears: 2,
    },
    includes: [
      'เครื่องชาร์จ DC 180 kW จำนวน 3 ตู้ (6 หัว)',
      'Transformer ~800 kVA · MDB · งานไฟฟ้า',
      'โครงสร้างหลังคา / canopy',
      'งานจุดจอด EV 6 ช่อง · ป้ายสถานี',
      'Internet / OCPP · CCTV พื้นฐาน',
      'ติดตั้ง ทดสอบ และรับประกัน 2 ปี',
    ],
    features: [
      'กำลังรวมสูงกว่า Hub 6×120 ประมาณ 50%',
      'แพลตฟอร์ม J3 180 kW',
      'เหมาะกับทราฟฟิกสูงในพื้นที่จำกัด',
      'รองรับรถ 800V',
    ],
    financials: {
      operatingHoursPerDay: 10,
      kwhPerDay: 5400,
      kwhPerMonth: 162000,
      sellPricePerKwh: 8,
      energyCostPerKwh: 2.8,
      revenueMonthly: 1296000,
      platformFeePct: 12,
      gpSharePct: 25,
      coordinatorPct: 10,
      investorPct: 90,
      investorNetMonthly: 515160,
      annualNet: 6181920,
      roiAnnualPct: 105.7,
      paybackMonths: 11.4,
      paybackYears: 1.0,
    },
    targetSites: ['gas', 'mall', 'highway', 'parking', 'public'],
    sortOrder: 32,
    image: '/images/packages/cx-hub-6-180.jpg',
    priceRateId: 'rate-dc-j-180',
    specId: 'spec-zd-j3',
  },
  {
    id: 'pkg-cx-hub-8-120',
    slug: 'cx-hub-8-120',
    code: 'CX-HUB-8-120',
    name: 'CX Hub 8 · 120 kW',
    nameTh: 'สถานีสำเร็จรูป CX Hub 8 หัว · 120 kW',
    productType: 'turnkey',
    sourceLabel: 'CX ENERTECH · EV Hub Turnkey Series',
    tagline: '8 หัวจ่าย · 4× DC 120 kW · กำลังรวม 480 kW',
    description:
      'Turnkey 8-nozzle hub with four 120 kW dual-gun chargers — สถานีสำเร็จรูป 8 หัว ใช้เครื่อง DC 120 kW ×4 สำหรับห้าง ปั๊ม และลานจอดขนาดใหญ่',
    powerKwMin: 480,
    powerKwMax: 480,
    chargerCount: 4,
    nozzleCountMin: 8,
    nozzleCountMax: 8,
    parkingBays: 8,
    transformerKva: 800,
    footprintWm: 24,
    footprintDm: 7.5,
    priceList: null,
    pricePromo: 6390000,
    priceCapex: 6390000,
    priceNote:
      'ราคาสำเร็จรูปรวมเครื่อง DC 120 kW ×4 (ราคาต่อหน่วย 1,550,000 บาท) ไฟฟ้า/หม้อแปลง canopy จุดจอด และ commissioning',
    roiAnnualPct: 86,
    paybackMonths: 14,
    paybackYears: 1.2,
    netProfitMonthly: 457920,
    specs: {
      chargers: '4 × DC 120 kW dual gun',
      nozzles: '8 (2 ต่อตู้)',
      totalPowerKw: 480,
      architecture: 'Integrated DC cabinets + canopy',
      electrical: 'Transformer 800 kVA + MDB',
      footprint: '≈ 24 × 7.5 m',
      warrantyYears: 2,
    },
    includes: [
      'เครื่องชาร์จ DC 120 kW จำนวน 4 ตู้ (8 หัว)',
      'Transformer ~800 kVA · MDB · งานไฟฟ้า',
      'โครงสร้างหลังคา / canopy',
      'งานจุดจอด EV 8 ช่อง · landscaping · ป้ายสถานี',
      'Internet / OCPP · CCTV 4 กล้อง',
      'ติดตั้ง ทดสอบ และรับประกัน 2 ปี',
    ],
    features: [
      '8 หัวชาร์จพร้อมกัน',
      'Layout สถานีมาตรฐาน',
      'สมดุลต้นทุนและทราฟฟิก',
      'ขยายไป Hub 10 ได้',
    ],
    financials: {
      operatingHoursPerDay: 10,
      kwhPerDay: 4800,
      kwhPerMonth: 144000,
      sellPricePerKwh: 8,
      energyCostPerKwh: 2.8,
      revenueMonthly: 1152000,
      platformFeePct: 12,
      gpSharePct: 25,
      coordinatorPct: 10,
      investorPct: 90,
      investorNetMonthly: 457920,
      annualNet: 5495040,
      roiAnnualPct: 86,
      paybackMonths: 14,
      paybackYears: 1.2,
    },
    targetSites: ['gas', 'mall', 'hotel', 'parking', 'public'],
    sortOrder: 33,
    image: '/images/packages/cx-hub-8-120.jpg',
    priceRateId: 'rate-dc-j-120',
    specId: 'spec-zd-j2',
  },
  {
    id: 'pkg-cx-hub-8-180',
    slug: 'cx-hub-8-180',
    code: 'CX-HUB-8-180',
    name: 'CX Hub 8 · 180 kW',
    nameTh: 'สถานีสำเร็จรูป CX Hub 8 หัว · 180 kW',
    productType: 'turnkey',
    sourceLabel: 'CX ENERTECH · EV Hub Turnkey Series',
    tagline: '8 หัวจ่าย · 4× DC 180 kW · กำลังรวม 720 kW',
    description:
      'Turnkey 8-nozzle high-power hub on 180 kW cabinets — สถานีสำเร็จรูป 8 หัว ใช้เครื่อง DC 180 kW ×4 สำหรับทราฟฟิกสูง',
    powerKwMin: 720,
    powerKwMax: 720,
    chargerCount: 4,
    nozzleCountMin: 8,
    nozzleCountMax: 8,
    parkingBays: 8,
    transformerKva: 1000,
    footprintWm: 24,
    footprintDm: 7.5,
    priceList: null,
    pricePromo: 7800000,
    priceCapex: 7800000,
    priceNote:
      'ราคาสำเร็จรูปรวมเครื่อง DC 180 kW ×4 ไฟฟ้า/หม้อแปลง canopy จุดจอด และ commissioning (ราคาเครื่อง 180 kW อ้างอิงประมาณการ)',
    roiAnnualPct: 105.7,
    paybackMonths: 11.4,
    paybackYears: 1.0,
    netProfitMonthly: 686880,
    specs: {
      chargers: '4 × DC 180 kW dual gun',
      nozzles: '8 (2 ต่อตู้)',
      totalPowerKw: 720,
      architecture: 'Integrated DC cabinets + canopy (J3 platform)',
      electrical: 'Transformer 1,000 kVA + MDB',
      footprint: '≈ 24 × 7.5 m',
      warrantyYears: 2,
    },
    includes: [
      'เครื่องชาร์จ DC 180 kW จำนวน 4 ตู้ (8 หัว)',
      'Transformer ~1,000 kVA · MDB · งานไฟฟ้า',
      'โครงสร้างหลังคา / canopy',
      'งานจุดจอด EV 8 ช่อง · landscaping · ป้ายสถานี',
      'Internet / OCPP · CCTV 4 กล้อง',
      'ติดตั้ง ทดสอบ และรับประกัน 2 ปี',
    ],
    features: [
      'กำลังรวม 720 kW สำหรับสถานีทราฟฟิกสูง',
      'แพลตฟอร์ม J3 180 kW',
      'ชาร์จหลายคันเร็วพร้อมกัน',
      'เหมาะกับห้างใหญ่ / ปั๊มหลัก',
    ],
    financials: {
      operatingHoursPerDay: 10,
      kwhPerDay: 7200,
      kwhPerMonth: 216000,
      sellPricePerKwh: 8,
      energyCostPerKwh: 2.8,
      revenueMonthly: 1728000,
      platformFeePct: 12,
      gpSharePct: 25,
      coordinatorPct: 10,
      investorPct: 90,
      investorNetMonthly: 686880,
      annualNet: 8242560,
      roiAnnualPct: 105.7,
      paybackMonths: 11.4,
      paybackYears: 1.0,
    },
    targetSites: ['gas', 'mall', 'highway', 'tourism', 'public'],
    sortOrder: 34,
    image: '/images/packages/cx-hub-8-180.jpg',
    priceRateId: 'rate-dc-j-180',
    specId: 'spec-zd-j3',
  },
  {
    id: 'pkg-cx-hub-10-120',
    slug: 'cx-hub-10-120',
    code: 'CX-HUB-10-120',
    name: 'CX Hub 10 · 120 kW',
    nameTh: 'สถานีสำเร็จรูป CX Hub 10 หัว · 120 kW',
    productType: 'turnkey',
    sourceLabel: 'CX ENERTECH · EV Hub Turnkey Series',
    tagline: '10 หัวจ่าย · 5× DC 120 kW · กำลังรวม 600 kW',
    description:
      'Turnkey 10-nozzle hub with five 120 kW dual-gun chargers — สถานีสำเร็จรูป 10 หัว ใช้เครื่อง DC 120 kW ×5 เทียบเคียงสเกล S10 แบบ turnkey',
    powerKwMin: 600,
    powerKwMax: 600,
    chargerCount: 5,
    nozzleCountMin: 10,
    nozzleCountMax: 10,
    parkingBays: 10,
    transformerKva: 1000,
    footprintWm: 30,
    footprintDm: 7.5,
    priceList: null,
    pricePromo: 7990000,
    priceCapex: 7990000,
    priceNote:
      'ราคาสำเร็จรูปรวมเครื่อง DC 120 kW ×5 (ราคาต่อหน่วย 1,550,000 บาท) ไฟฟ้า/หม้อแปลง canopy จุดจอด และ commissioning',
    roiAnnualPct: 86,
    paybackMonths: 14,
    paybackYears: 1.2,
    netProfitMonthly: 572400,
    specs: {
      chargers: '5 × DC 120 kW dual gun',
      nozzles: '10 (2 ต่อตู้)',
      totalPowerKw: 600,
      architecture: 'Integrated DC cabinets + canopy',
      electrical: 'Transformer 1,000 kVA + MDB',
      footprint: '≈ 30 × 7.5 m',
      warrantyYears: 2,
    },
    includes: [
      'เครื่องชาร์จ DC 120 kW จำนวน 5 ตู้ (10 หัว)',
      'Transformer ~1,000 kVA · MDB · งานไฟฟ้า',
      'โครงสร้างหลังคา / canopy',
      'งานจุดจอด EV 10 ช่อง · landscaping · ป้ายสถานี',
      'Internet / OCPP · CCTV 4–6 กล้อง',
      'ติดตั้ง ทดสอบ และรับประกัน 2 ปี',
    ],
    features: [
      '10 หัวชาร์จพร้อมกัน',
      'สเกลสถานีใหญ่แบบสำเร็จรูป',
      'Layout มาตรฐาน CX ENERTECH',
      'ทางเลือก turnkey ของไลน์ 10 จุด',
    ],
    financials: {
      operatingHoursPerDay: 10,
      kwhPerDay: 6000,
      kwhPerMonth: 180000,
      sellPricePerKwh: 8,
      energyCostPerKwh: 2.8,
      revenueMonthly: 1440000,
      platformFeePct: 12,
      gpSharePct: 25,
      coordinatorPct: 10,
      investorPct: 90,
      investorNetMonthly: 572400,
      annualNet: 6868800,
      roiAnnualPct: 86,
      paybackMonths: 14,
      paybackYears: 1.2,
    },
    targetSites: ['mall', 'gas', 'tourism', 'public', 'highway'],
    sortOrder: 35,
    image: '/images/packages/cx-hub-10-120.jpg',
    priceRateId: 'rate-dc-j-120',
    specId: 'spec-zd-j2',
  },
  {
    id: 'pkg-cx-hub-10-180',
    slug: 'cx-hub-10-180',
    code: 'CX-HUB-10-180',
    name: 'CX Hub 10 · 180 kW',
    nameTh: 'สถานีสำเร็จรูป CX Hub 10 หัว · 180 kW',
    productType: 'turnkey',
    sourceLabel: 'CX ENERTECH · EV Hub Turnkey Series',
    tagline: '10 หัวจ่าย · 5× DC 180 kW · กำลังรวม 900 kW',
    description:
      'Flagship turnkey hub with ten nozzles on 180 kW cabinets — สถานีสำเร็จรูป 10 หัว ใช้เครื่อง DC 180 kW ×5 สำหรับฮับชาร์จความจุสูง',
    powerKwMin: 900,
    powerKwMax: 900,
    chargerCount: 5,
    nozzleCountMin: 10,
    nozzleCountMax: 10,
    parkingBays: 10,
    transformerKva: 1250,
    footprintWm: 30,
    footprintDm: 8,
    priceList: null,
    pricePromo: 9750000,
    priceCapex: 9750000,
    priceNote:
      'ราคาสำเร็จรูปรวมเครื่อง DC 180 kW ×5 ไฟฟ้า/หม้อแปลง canopy จุดจอด และ commissioning (ราคาเครื่อง 180 kW อ้างอิงประมาณการ)',
    roiAnnualPct: 105.7,
    paybackMonths: 11.4,
    paybackYears: 1.0,
    netProfitMonthly: 858600,
    specs: {
      chargers: '5 × DC 180 kW dual gun',
      nozzles: '10 (2 ต่อตู้)',
      totalPowerKw: 900,
      architecture: 'Integrated DC cabinets + canopy (J3 platform)',
      electrical: 'Transformer 1,250 kVA + MDB',
      footprint: '≈ 30 × 8 m',
      warrantyYears: 2,
    },
    includes: [
      'เครื่องชาร์จ DC 180 kW จำนวน 5 ตู้ (10 หัว)',
      'Transformer ~1,250 kVA · MDB · งานไฟฟ้า',
      'โครงสร้างหลังคา / canopy',
      'งานจุดจอด EV 10 ช่อง · landscaping · ป้ายสถานี',
      'Internet / OCPP · CCTV 6 กล้อง',
      'ติดตั้ง ทดสอบ และรับประกัน 2 ปี',
    ],
    features: [
      'กำลังรวม 900 kW — ฮับความจุสูง',
      '10 หัวชาร์จเร็วพร้อมกัน',
      'แพลตฟอร์ม J3 180 kW',
      'เหมาะกับฮับหลัก / ทางหลวง / ห้างใหญ่',
    ],
    financials: {
      operatingHoursPerDay: 10,
      kwhPerDay: 9000,
      kwhPerMonth: 270000,
      sellPricePerKwh: 8,
      energyCostPerKwh: 2.8,
      revenueMonthly: 2160000,
      platformFeePct: 12,
      gpSharePct: 25,
      coordinatorPct: 10,
      investorPct: 90,
      investorNetMonthly: 858600,
      annualNet: 10303200,
      roiAnnualPct: 105.7,
      paybackMonths: 11.4,
      paybackYears: 1.0,
    },
    targetSites: ['highway', 'mall', 'gas', 'tourism', 'hub'],
    sortOrder: 36,
    image: '/images/packages/cx-hub-10-180.jpg',
    priceRateId: 'rate-dc-j-180',
    specId: 'spec-zd-j3',
  },

  {
    id: 'pkg-cx-dc30',
    slug: 'cx-dc-30',
    code: 'CX-DC30',
    name: 'CX DC 30 (J1)',
    nameTh: 'เครื่องชาร์จ CX DC 30 (J1)',
    productType: 'equipment',
    sourceLabel: 'ZeedaDirect ZD-DC-J1 · 30-60 kW.pdf',
    tagline: '30 kW · CCS2 · ZD-DC-J1 · Sell 179,000 / ราคาแนะนำขาย',
    description:
      '30 kW single-gun DC charger on ZeedaDirect J1 platform — เครื่องชาร์จ DC 30 kW หัวเดียว แพลตฟอร์ม J1 สำหรับโรงแรม ร้านอาหาร และ SME',
    powerKwMin: 30,
    powerKwMax: 30,
    chargerCount: 1,
    nozzleCountMin: 1,
    nozzleCountMax: 1,
    parkingBays: 1,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: 179000,
    pricePromo: 140000,
    priceCapex: null,
    priceNote: 'ราคาแนะนำขายอ้างอิงจากเรทเครื่อง CX DC 30 / Recommended sell from CX DC 30 rate',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      model: 'ZD-DC-J1',
      power: '30 kW',
      ratedVoltage: 'CCS2 1000V DC',
      maxCurrent: 'CCS2 100A',
      cables: 'Single',
      ipRating: 'IP54',
      protocol: 'OCPP1.6J / OCPP2.0',
      screen: '8" LCD',
      dimensions: '690 × 584 × 1686 mm',
    },
    includes: ['ZD-DC-J1 30 kW', 'CCS2 cable', '8" touchscreen', 'OCPP ready'],
    features: [
      'Opportunity / destination charging',
      'Modular · CE / TUV SUD',
      'Remote monitoring + OTA',
      'Ideal for hotel / F&B / SME',
    ],
    financials: null,
    targetSites: ['hotel', 'restaurant', 'sme', 'factory'],
    sortOrder: 40,
    image: '/images/packages/cx-dc-j1.jpg',
    priceRateId: null,
    specId: 'spec-zd-j1',
  },
  {
    id: 'pkg-cx-dc40',
    slug: 'cx-dc-40',
    code: 'CX-DC40',
    name: 'CX DC 40 (J2)',
    nameTh: 'เครื่องชาร์จ CX DC 40 (J2)',
    productType: 'equipment',
    sourceLabel: 'ZeedaDirect ZD-DC-J2 · 40-160 kW.pdf',
    tagline: '40 kW · CCS2 200A · ZD-DC-J2 · Sell 350,100 / ราคาแนะนำขาย',
    description:
      '40 kW DC charger on ZeedaDirect J2 platform (40–160 kW family) — เครื่องชาร์จ DC 40 kW แพลตฟอร์ม J2',
    powerKwMin: 40,
    powerKwMax: 40,
    chargerCount: 1,
    nozzleCountMin: 1,
    nozzleCountMax: 2,
    parkingBays: 1,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: 350100,
    pricePromo: 280000,
    priceCapex: null,
    priceNote: 'ราคาแนะนำขายอ้างอิงจากเรทเครื่อง CX DC 40 / Recommended sell from CX DC 40 rate',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      model: 'ZD-DC-J2',
      power: '40 kW',
      ratedVoltage: 'CCS2 1000V DC',
      maxCurrent: 'CCS2 200A',
      ipRating: 'IP54',
      protocol: 'OCPP1.6J / OCPP2.0.1',
      screen: '8" LCD',
      auth: 'APP / RFID / NFC / Credit Card',
      dimensions: '700 × 490 × 1696 mm',
    },
    includes: ['ZD-DC-J2 40 kW', 'CCS2 cables', '8" touchscreen', 'OCPP ready'],
    features: ['Modular mid-power platform', 'Multi-auth payment ready', 'CE / TUV SUD', 'OTA upgrades'],
    financials: null,
    targetSites: ['commercial', 'mall', 'office'],
    sortOrder: 45,
    image: '/images/packages/cx-dc-j2.jpg',
    priceRateId: null,
    specId: 'spec-zd-j2',
  },
  {
    id: 'pkg-cx-dc60',
    slug: 'cx-dc-60',
    code: 'CX-DC60',
    name: 'CX DC 60 S (ZEC)',
    nameTh: 'เครื่องชาร์จ CX DC 60 S (ZEC)',
    productType: 'equipment',
    sourceLabel: 'ZEC 60kW DC Charger · S-Series price sheet',
    tagline: '60 kW · S-Series · Sell 468,000 / ราคาแนะนำขาย',
    description:
      'ZEC 60 kW integrated DC fast charger — เครื่องชาร์จ DC 60 kW ไลน์ S-Series พร้อมตารางราคาขาย-ต้นทุน',
    powerKwMin: 60,
    powerKwMax: 60,
    chargerCount: 1,
    nozzleCountMin: 1,
    nozzleCountMax: 2,
    parkingBays: 1,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: 468000,
    pricePromo: 360000,
    priceCapex: null,
    priceNote:
      'ราคาแนะนำขาย 468,000 · ต้นทุนเริ่ม 360,000 (<3, S-Series) / Sell 468k · Cost from 360k',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      model: 'ZEC-60',
      series: 'S-Series',
      input: '400 VAC ±10% · 3P+N+PE · 112 A',
      ratedPower: 'DC 60 kW',
      outputVoltage: 'CCS2 200–1000 Vdc',
      efficiency: '96%',
      ipIk: 'IP55 / IK10',
      protocol: 'OCPP 1.6J',
    },
    includes: ['ZEC 60 kW DC Fast Charger', 'CCS2 cable 5 m', 'RFID / OCPP 1.6J', 'CE / TUV'],
    features: ['S-Series sell/cost tiers', 'Multi-connector options', 'IP55/IK10', 'Compact integrated'],
    financials: null,
    targetSites: ['commercial', 'mall', 'depot', 'station'],
    sortOrder: 50,
    image: '/images/packages/cx-dc-60.jpg',
    priceRateId: 'rate-dc-s-60',
    specId: 'spec-zec-60',
  },
  {
    id: 'pkg-cx-dc60-j',
    slug: 'cx-dc-60-j',
    code: 'CX-DC60-J',
    name: 'CX DC 60 J',
    nameTh: 'เครื่องชาร์จ CX DC 60 J',
    productType: 'equipment',
    sourceLabel: 'ZeedaDirect ZD-DC-J1 · J-Series price sheet',
    tagline: '60 kW · J-Series · Sell 364,000 / ราคาแนะนำขาย',
    description:
      '60 kW dual-ready DC on ZeedaDirect J1 — เครื่องชาร์จ DC 60 kW ไลน์ J-Series ราคาแนะนำขายจากตารางราคา',
    powerKwMin: 60,
    powerKwMax: 60,
    chargerCount: 1,
    nozzleCountMin: 1,
    nozzleCountMax: 2,
    parkingBays: 1,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: 364000,
    pricePromo: 280000,
    priceCapex: null,
    priceNote:
      'ราคาแนะนำขาย 364,000 · ต้นทุนเริ่ม 280,000 (<3, J-Series) / Sell 364k · Cost from 280k',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      model: 'ZD-DC-J1',
      series: 'J-Series',
      power: '60 kW',
      ratedVoltage: 'CCS2 1000V DC',
      maxCurrent: 'CCS2 200A',
      cables: 'Dual',
      ipRating: 'IP54',
      protocol: 'OCPP1.6J / OCPP2.0',
      screen: '8" LCD',
      dimensions: '690 × 584 × 1686 mm',
    },
    includes: ['ZD-DC-J1 60 kW', 'Dual CCS2 ready', '8" touchscreen', 'OCPP ready'],
    features: ['J-Series sell/cost tiers', 'CE / TUV SUD', 'Remote + OTA', 'Destination charging'],
    financials: null,
    targetSites: ['commercial', 'mall', 'hotel', 'sme'],
    sortOrder: 52,
    image: '/images/packages/cx-dc-j1.jpg',
    priceRateId: 'rate-dc-j-60',
    specId: 'spec-zd-j1',
  },
  {
    id: 'pkg-cx-dc120',
    slug: 'cx-dc-120',
    code: 'CX-DC120',
    name: 'CX DC 120 S (ZEC)',
    nameTh: 'เครื่องชาร์จ CX DC 120 S (ZEC)',
    productType: 'equipment',
    sourceLabel: 'ZEC 120kW DC Charger · S-Series price sheet',
    tagline: '120 kW · S-Series · Sell 676,000 / ราคาแนะนำขาย',
    description:
      'ZEC 120 kW outdoor integrated DC charger — เครื่องชาร์จ DC 120 kW ไลน์ S-Series พร้อมตารางราคาขาย-ต้นทุน',
    powerKwMin: 120,
    powerKwMax: 120,
    chargerCount: 1,
    nozzleCountMin: 1,
    nozzleCountMax: 2,
    parkingBays: 2,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: 676000,
    pricePromo: 520000,
    priceCapex: null,
    priceNote:
      'ราคาแนะนำขาย 676,000 · ต้นทุนเริ่ม 520,000 (<3, S-Series) / Sell 676k · Cost from 520k',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      model: 'ZEC-120',
      series: 'S-Series',
      input: '400 VAC ±10% · 3P+N+PE · 224 A',
      ratedPower: 'DC 120 kW',
      outputVoltage: 'CCS2 200–1000 Vdc',
      efficiency: '96%',
      ipIk: 'IP55 / IK10',
      protocol: 'OCPP 1.6J',
    },
    includes: ['ZEC 120 kW DC Fast Charger', 'CCS2 cable 5 m', 'RFID / OCPP 1.6J', 'CE / TUV'],
    features: ['S-Series sell/cost tiers', 'Single or dual connector', 'IP55/IK10', 'Power sharing'],
    financials: null,
    targetSites: ['station', 'mall', 'gas', 'depot'],
    sortOrder: 55,
    image: '/images/packages/cx-dc-120.jpg',
    priceRateId: 'rate-dc-s-120',
    specId: 'spec-zec-120',
  },
  {
    id: 'pkg-cx-dc120-j',
    slug: 'cx-dc-120-j',
    code: 'CX-DC120-J',
    name: 'CX DC 120 J',
    nameTh: 'เครื่องชาร์จ CX DC 120 J',
    productType: 'equipment',
    sourceLabel: 'ZeedaDirect ZD-DC-J2 · J-Series price sheet',
    tagline: '120 kW · J-Series · Sell 494,000 / ราคาแนะนำขาย',
    description:
      '120 kW DC on ZeedaDirect J2 (40–160 kW family) — เครื่องชาร์จ DC 120 kW ไลน์ J-Series จากตารางราคา',
    powerKwMin: 120,
    powerKwMax: 120,
    chargerCount: 1,
    nozzleCountMin: 1,
    nozzleCountMax: 2,
    parkingBays: 2,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: 494000,
    pricePromo: 380000,
    priceCapex: null,
    priceNote:
      'ราคาแนะนำขาย 494,000 · ต้นทุนเริ่ม 380,000 (<3, J-Series) / Sell 494k · Cost from 380k',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      model: 'ZD-DC-J2',
      series: 'J-Series',
      power: '120 kW',
      ratedVoltage: 'CCS2 1000V DC',
      maxCurrent: 'CCS2 200A',
      cableLength: '5m × 2 or 7m × 2',
      ipRating: 'IP54',
      protocol: 'OCPP1.6J / OCPP2.0.1',
      auth: 'APP / RFID / NFC / Credit Card',
      dimensions: '700 × 490 × 1696 mm',
    },
    includes: ['ZD-DC-J2 120 kW', 'Dual CCS2 ready', '8" touchscreen', 'OCPP ready'],
    features: ['J-Series sell/cost tiers', 'Multi-auth payment', 'CE / TUV SUD', 'OTA upgrades'],
    financials: null,
    targetSites: ['station', 'mall', 'gas', 'commercial'],
    sortOrder: 57,
    image: '/images/packages/cx-dc-j2.jpg',
    priceRateId: 'rate-dc-j-120',
    specId: 'spec-zd-j2',
  },
  {
    id: 'pkg-cx-dc180',
    slug: 'cx-dc-180',
    code: 'CX-DC180',
    name: 'CX DC 180 J',
    nameTh: 'เครื่องชาร์จ CX DC 180 J',
    productType: 'equipment',
    sourceLabel: 'ZeedaDirect ZD-DC-J3 · 160-240 kW.pdf',
    tagline: '180 kW · J3 platform · Price pending / รออัปเดตราคา',
    description:
      '180 kW DC on ZeedaDirect J3 (160/180/240 kW) — เครื่องชาร์จ DC 180 kW แพลตฟอร์ม J3 (รอราคาในตาราง J-Series)',
    powerKwMin: 180,
    powerKwMax: 180,
    chargerCount: 1,
    nozzleCountMin: 2,
    nozzleCountMax: 2,
    parkingBays: 2,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: null,
    pricePromo: null,
    priceCapex: null,
    priceNote: 'รออัปเดตราคา J-Series 180 kW / Price pending on J-Series sheet',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      model: 'ZD-DC-J3',
      series: 'J-Series',
      power: '180 kW',
      ratedVoltage: 'CCS2 1000V DC',
      maxCurrent: 'CCS2 250A',
      cableLength: '5m × 2 or 7m × 2',
      ipRating: 'IP54',
      protocol: 'OCPP 1.6J / 2.0.1',
      screen: '8" LCD',
      dimensions: '750 × 605 × 1805 mm',
    },
    includes: ['ZD-DC-J3 180 kW', 'Dual connector', '8" touchscreen', 'OCPP ready'],
    features: ['High-power station ready', 'Multi-auth payment', 'CE / TUV SUD', 'OTA upgrades'],
    financials: null,
    targetSites: ['station', 'hub', 'gas', 'depot'],
    sortOrder: 60,
    image: '/images/packages/cx-dc-j3.jpg',
    priceRateId: 'rate-dc-j-180',
    specId: 'spec-zd-j3',
  },
  {
    id: 'pkg-cx-dc240-j',
    slug: 'cx-dc-240-j',
    code: 'CX-DC240-J',
    name: 'CX DC 240 J',
    nameTh: 'เครื่องชาร์จ CX DC 240 J',
    productType: 'equipment',
    sourceLabel: 'ZeedaDirect ZD-DC-J3 / J4 · 160-240 & 240-420 kW.pdf',
    tagline: '240 kW · J3/J4 · Price pending / รออัปเดตราคา',
    description:
      '240 kW DC available on J3 (160–240) or J4 (240–420) platforms — เครื่องชาร์จ DC 240 kW (รอราคาในตาราง J-Series)',
    powerKwMin: 240,
    powerKwMax: 240,
    chargerCount: 1,
    nozzleCountMin: 2,
    nozzleCountMax: 2,
    parkingBays: 2,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: null,
    pricePromo: null,
    priceCapex: null,
    priceNote: 'รออัปเดตราคา J-Series 240 kW / Price pending on J-Series sheet',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      model: 'ZD-DC-J3 / J4',
      series: 'J-Series',
      power: '240 kW',
      ratedVoltage: 'CCS2 1000V DC',
      maxCurrent: 'CCS2 400A',
      ipRating: 'IP54',
      protocol: 'OCPP1.6J / OCPP2.0',
      screen: '8" LCD',
    },
    includes: ['ZD-DC-J3 or J4 240 kW', 'Dual connector', '8" touchscreen', 'OCPP ready'],
    features: ['Ultra-fast corridor ready', 'Multi-auth payment', 'CE certified', 'OTA upgrades'],
    financials: null,
    targetSites: ['hub', 'highway', 'depot', 'gas'],
    sortOrder: 62,
    image: '/images/packages/cx-dc-j4.jpg',
    priceRateId: 'rate-dc-j-240',
    specId: 'spec-zd-j4',
  },
  {
    id: 'pkg-cx-dc30p',
    slug: 'cx-dc-30-pay',
    code: 'CX-DC30P',
    name: 'CX DC 30 Pay',
    nameTh: 'เครื่องชาร์จ CX DC 30 Pay',
    productType: 'equipment',
    sourceLabel: 'CX ENERTECH · DC Pay Series',
    tagline: '30 kW · RFID/QR · Payment ready / พร้อมระบบชำระเงิน',
    description:
      'DC 30 kW charger with built-in payment — เครื่องชาร์จ DC 30 kW พร้อมระบบชำระเงินในตัว สำหรับโรงแรม ร้านอาหาร และ SME',
    powerKwMin: 30,
    powerKwMax: 30,
    chargerCount: 1,
    nozzleCountMin: 1,
    nozzleCountMax: 1,
    parkingBays: 1,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: 179000,
    pricePromo: 179000,
    priceCapex: null,
    priceNote: 'ราคาเครื่องอ้างอิงรวมระบบชำระเงิน / Includes payment system',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      model: 'CX DC 30 Pay',
      powerKw: 30,
      auth: 'RFID + QR',
      payment: 'Scan to Pay',
      display: 'Yes',
    },
    includes: ['CX DC 30 Pay', 'Scan to Pay', 'Display', 'RFID / QR'],
    features: [
      'Up to 30 kW DC',
      'Safety certified platform',
      'Easy display UI',
      'Ready for paid charging',
    ],
    financials: null,
    targetSites: ['hotel', 'restaurant', 'factory', 'sme'],
    sortOrder: 70,
    image: '/images/packages/cx-dc-30-pay.jpg',
    priceRateId: null,
    specId: null,
  },
  {
    id: 'pkg-cx-ac7-g',
    slug: 'cx-ac-7-g',
    code: 'CX-AC7-G',
    name: 'CX AC 7 G',
    nameTh: 'เครื่องชาร์จ CX AC 7 G',
    productType: 'equipment',
    sourceLabel: 'ZD Energy G Series · AC price sheet',
    tagline: '7.4 kW · 1P · Sell 13,500 / ราคาแนะนำขาย',
    description:
      'G-Series 7.4 kW single-phase AC wallbox — เครื่องชาร์จ AC G-Series ราคาแนะนำขายจากตารางราคา AC',
    powerKwMin: 7,
    powerKwMax: 7,
    chargerCount: 1,
    nozzleCountMin: 1,
    nozzleCountMax: 1,
    parkingBays: 1,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: 13500,
    pricePromo: 7500,
    priceCapex: null,
    priceNote: 'ราคาแนะนำขาย 13,500 · ต้นทุนเริ่ม 7,500 (<3) / Sell 13.5k · Cost from 7.5k',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      model: 'ZD-AC-G',
      series: 'G-Series',
      power: '7.4 kW (3.7 option)',
      voltage: 'AC 230V',
      current: '32A',
      phase: '1P',
      ipRating: 'IP55',
      protocol: 'OCPP1.6JSON',
      dimensions: '310 × 214 × 90 mm',
    },
    includes: ['G-Series 7.4 kW charger', '7 m cable', 'Wall mount', 'Optional RFID'],
    features: ['Compact & light', 'Home / light commercial', 'OCPP ready', 'Multi-protection'],
    financials: null,
    targetSites: ['home', 'condo', 'sme', 'office'],
    sortOrder: 80,
    image: '/images/packages/cx-ac-g7.jpg',
    priceRateId: 'rate-ac-g-7',
    specId: 'spec-ac-g-7',
  },
  {
    id: 'pkg-cx-ac7-k',
    slug: 'cx-ac-7-k',
    code: 'CX-AC7-K',
    name: 'CX AC 7 K',
    nameTh: 'เครื่องชาร์จ CX AC 7 K',
    productType: 'equipment',
    sourceLabel: 'ZD Energy K Series · AC price sheet',
    tagline: '7.4 kW · 1P · IP66 · Sell 15,300 / ราคาแนะนำขาย',
    description:
      'K-Series 7.4 kW rugged AC wallbox (IP66 shell) — เครื่องชาร์จ AC K-Series เปลือกกันน้ำสูง ราคาจากตาราง AC',
    powerKwMin: 7,
    powerKwMax: 7,
    chargerCount: 1,
    nozzleCountMin: 1,
    nozzleCountMax: 1,
    parkingBays: 1,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: 15300,
    pricePromo: 8500,
    priceCapex: null,
    priceNote: 'ราคาแนะนำขาย 15,300 · ต้นทุนเริ่ม 8,500 (<3) / Sell 15.3k · Cost from 8.5k',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      model: 'ZD-AC-K',
      series: 'K-Series',
      power: '7.4 kW (3.7 option)',
      voltage: 'AC 230V',
      current: '32A',
      phase: '1P',
      ipRating: 'IP66 shell / IP55 gun',
      protocol: 'OCPP 1.6 JSON',
      dimensions: '420 × 251 × 145 mm',
    },
    includes: ['K-Series 7.4 kW charger', '7 m cable', 'Wall mount', 'Optional RFID / WiFi'],
    features: ['IP66 outdoor shell', 'OCPP ready', 'Multi-protection', 'Pedestal option'],
    financials: null,
    targetSites: ['home', 'condo', 'parking', 'sme'],
    sortOrder: 82,
    image: '/images/packages/cx-ac-k7.jpg',
    priceRateId: 'rate-ac-k-7',
    specId: 'spec-ac-k-7',
  },
  {
    id: 'pkg-cx-ac7-miniz',
    slug: 'cx-ac-7-miniz',
    code: 'CX-AC7-MINIZ',
    name: 'CX AC 7 Mini Z',
    nameTh: 'เครื่องชาร์จ CX AC 7 Mini Z',
    productType: 'equipment',
    sourceLabel: 'Mini Z-Series · AC price sheet',
    tagline: '7 kW · 1P · Sell 9,900 / ราคาแนะนำขาย',
    description:
      'Entry Mini Z-Series 7 kW AC wallbox — เครื่องชาร์จ AC รุ่นประหยัด ราคาแนะนำขายจากตาราง AC',
    powerKwMin: 7,
    powerKwMax: 7,
    chargerCount: 1,
    nozzleCountMin: 1,
    nozzleCountMax: 1,
    parkingBays: 1,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: 9900,
    pricePromo: 5500,
    priceCapex: null,
    priceNote: 'ราคาแนะนำขาย 9,900 · ต้นทุนเริ่ม 5,500 (<3) / Sell 9.9k · Cost from 5.5k',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      model: 'ZD-AC-MINIZ',
      series: 'Mini Z-Series',
      power: '7 kW',
      phase: '1P',
      form: 'Compact wallbox',
    },
    includes: ['Mini Z 7 kW charger', 'Wall mount'],
    features: ['Entry price point', 'Residential ready', 'Compact install'],
    financials: null,
    targetSites: ['home', 'condo', 'sme'],
    sortOrder: 84,
    image: '/images/packages/cx-ac-miniz.jpg',
    priceRateId: 'rate-ac-miniz-7',
    specId: 'spec-ac-miniz-7',
  },
  {
    id: 'pkg-cx-ac11-e',
    slug: 'cx-ac-11-e',
    code: 'CX-AC11-E',
    name: 'CX AC 11 E',
    nameTh: 'เครื่องชาร์จ CX AC 11 E',
    productType: 'equipment',
    sourceLabel: 'ZD Energy E Series · AC price sheet',
    tagline: '11 kW · 3P · Sell 23,400 / ราคาแนะนำขาย',
    description:
      'E-Series 11 kW three-phase AC charger — เครื่องชาร์จ AC E-Series 11 kW สามเฟส จากตารางราคา AC',
    powerKwMin: 11,
    powerKwMax: 11,
    chargerCount: 1,
    nozzleCountMin: 1,
    nozzleCountMax: 1,
    parkingBays: 1,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: 23400,
    pricePromo: 13000,
    priceCapex: null,
    priceNote: 'ราคาแนะนำขาย 23,400 · ต้นทุนเริ่ม 13,000 (<3) / Sell 23.4k · Cost from 13k',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      model: 'ZD-AC-E',
      series: 'E-Series',
      power: '11 kW',
      voltage: 'AC 400V',
      current: '16A option / 32A platform',
      phase: '3P',
      ipRating: 'IP55',
      protocol: 'OCPP1.6JSON',
      dimensions: '473 × 290 × 160 mm',
    },
    includes: ['E-Series 11 kW charger', '7 m cable', 'Wall mount', 'Optional RFID / WiFi'],
    features: ['Three-phase commercial', 'IP55', 'OCPP ready', 'Multi-protection'],
    financials: null,
    targetSites: ['office', 'hotel', 'mall', 'parking'],
    sortOrder: 86,
    image: '/images/packages/cx-ac-e.jpg',
    priceRateId: 'rate-ac-e-11',
    specId: 'spec-ac-e',
  },
  {
    id: 'pkg-cx-ac22-e',
    slug: 'cx-ac-22-e',
    code: 'CX-AC22-E',
    name: 'CX AC 22 E',
    nameTh: 'เครื่องชาร์จ CX AC 22 E',
    productType: 'equipment',
    sourceLabel: 'ZD Energy E Series · AC price sheet',
    tagline: '22 kW · 3P · Sell 27,000 / ราคาแนะนำขาย',
    description:
      'E-Series 22 kW three-phase AC charger — เครื่องชาร์จ AC E-Series 22 kW สามเฟส จากตารางราคา AC',
    powerKwMin: 22,
    powerKwMax: 22,
    chargerCount: 1,
    nozzleCountMin: 1,
    nozzleCountMax: 1,
    parkingBays: 1,
    transformerKva: null,
    footprintWm: null,
    footprintDm: null,
    priceList: 27000,
    pricePromo: 15000,
    priceCapex: null,
    priceNote: 'ราคาแนะนำขาย 27,000 · ต้นทุนเริ่ม 15,000 (<3) / Sell 27k · Cost from 15k',
    roiAnnualPct: null,
    paybackMonths: null,
    netProfitMonthly: null,
    specs: {
      model: 'ZD-AC-E',
      series: 'E-Series',
      power: '22 kW',
      voltage: 'AC 400V',
      current: '32A',
      phase: '3P',
      ipRating: 'IP55',
      protocol: 'OCPP1.6JSON',
      dimensions: '473 × 290 × 160 mm',
    },
    includes: ['E-Series 22 kW charger', '7 m cable', 'Wall mount', 'Optional RFID / WiFi'],
    features: ['Fast AC commercial', 'IP55', 'OCPP ready', 'Multi-protection'],
    financials: null,
    targetSites: ['office', 'hotel', 'mall', 'parking', 'depot'],
    sortOrder: 88,
    image: '/images/packages/cx-ac-e.jpg',
    priceRateId: 'rate-ac-e-22',
    specId: 'spec-ac-e',
  },
]
